-- Tạo hàm cập nhật thời gian (Fix lỗi 42883)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';
-- ==================================================================================
-- BITPAW OS - PRODUCTION DEPLOYMENT PATCH v1
-- Target Database Engine: PostgreSQL 15+ / Supabase compatible
--
-- Gộp chung 3 migration của phiên làm việc go-live hôm nay, chạy 1 lần duy nhất
-- theo đúng thứ tự bên dưới trên Supabase SQL Editor trước khi lên Production:
--   1) supabase_schema_patch_final_audit.sql   (fix audit cuối)
--   2) supabase_schema_patch_fnb_refactor.sql  (hồi sinh Kitchen Display)
--   3) supabase_schema_patch_hr_bridge.sql     (cầu nối HR an toàn)
--
-- An toàn: TOÀN BỘ đều là additive (ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT
-- EXISTS / CREATE OR REPLACE FUNCTION / CREATE TRIGGER, có DROP TRIGGER IF EXISTS
-- trước khi tạo lại). Không XÓA hay sửa đổi bất kỳ dữ liệu/bảng nào đang có sẵn.
-- Idempotent — chạy lại nhiều lần không gây lỗi hay trùng lặp.
-- Yêu cầu: các bảng orders, order_items, staff, dining_tables, employees phải đã
-- tồn tại từ schema gốc trước khi chạy file này. Không có bảng `businesses` riêng —
-- business_id trong hệ thống này chính là auth.users.id (mỗi chủ tiệm = 1 user
-- Supabase Auth), nên các cột business_id bên dưới KHÔNG có ràng buộc FK.
-- ==================================================================================


-- ==================================================================================
-- PHẦN 1/3 — FIX AUDIT CUỐI (business_id trigger cho AI CSKH + salary_config)
-- ==================================================================================

-- 1.1 Tự động điền business_id trên orders/order_items từ JWT claim của request,
--     thay vì tin tưởng client gửi lên. spa.html và karaoke.html đã nâng cấp
--     Supabase client mang theo JWT ngắn hạn chứa claim `business_id` (được mint
--     server-side bởi _mint_tenant_jwt trong app.py, dùng để RLS lọc đúng tenant)
--     — nhưng chưa có gì copy claim đó vào chính dòng dữ liệu, nên mọi
--     order/order_item ghi từ 2 trang đó đều có business_id = NULL. Điều này làm
--     hỏng tính năng tra cứu lịch sử mua hàng của AIContextEngine
--     (ai_context_engine.py), vốn lọc chặt theo business_id + customer_phone nên
--     luôn trả về rỗng.
--
--     Trigger này đọc ĐÚNG JWT claim RLS đã dùng sẵn
--     (current_setting('request.jwt.claims', true)::json ->> 'business_id') và,
--     nếu business_id của dòng mới là NULL, tự điền vào ở phía server. Cố tình
--     KHÔNG sửa client-side JS — business_id không phải thứ nên để trình duyệt
--     tự set.

CREATE OR REPLACE FUNCTION set_business_id_from_jwt()
RETURNS TRIGGER AS $$
DECLARE
    jwt_business_id TEXT;
BEGIN
    IF NEW.business_id IS NULL THEN
        jwt_business_id := current_setting('request.jwt.claims', true)::json ->> 'business_id';
        IF jwt_business_id IS NOT NULL THEN
            NEW.business_id := jwt_business_id::uuid;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_orders_set_business_id ON orders;
CREATE TRIGGER trg_orders_set_business_id
    BEFORE INSERT ON orders
    FOR EACH ROW EXECUTE FUNCTION set_business_id_from_jwt();

DROP TRIGGER IF EXISTS trg_order_items_set_business_id ON order_items;
CREATE TRIGGER trg_order_items_set_business_id
    BEFORE INSERT ON order_items
    FOR EACH ROW EXECUTE FUNCTION set_business_id_from_jwt();

-- 1.2 cauhinh_luong.html bấm "Lưu" gọi POST /api/cauhinh_luong/<staff_id>, một route
--     Flask trước đây không hề tồn tại — luôn lỗi 404. Bảng `staff` không có cột cho
--     các trường lương chi tiết trang này chỉnh (luong_cung, luong_gio, hoa_hong,
--     phu_cap, tang_ca), nên lưu dưới dạng 1 JSON blob linh hoạt thay vì thêm 5 cột
--     hẹp riêng lẻ.
--
--     LƯU Ý: đây là fix RIÊNG, hẹp hơn hệ thống lương/chấm công thật khác của app
--     (bảng `employees` + `chamcong`, dùng bởi nhanvien.html/bangluong.html, không
--     có trong bất kỳ file schema nào được version-control). cauhinh_luong.html vận
--     hành trên bảng `staff` (qua staff_id) — một hệ đăng ký khác với `employees`
--     (khoá bằng ma_nv). Phần 3 bên dưới nối 2 hệ này lại một cách an toàn.
ALTER TABLE staff ADD COLUMN IF NOT EXISTS salary_config JSONB DEFAULT '{}'::jsonb;


-- ==================================================================================
-- PHẦN 2/3 — HỒI SINH KITCHEN DISPLAY (F&B)
-- ==================================================================================

-- Tạo bảng kitchen_orders thật, hỗ trợ vòng đời vé bếp 3 trạng thái
-- (pending -> cooking -> completed) theo đúng yêu cầu nghiệp vụ.
CREATE TABLE IF NOT EXISTS public.kitchen_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID, -- = auth.users.id của chủ tiệm; không có bảng businesses riêng nên không đặt FK
    table_id BIGINT REFERENCES public.dining_tables(id) ON DELETE SET NULL,
    table_name TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'cooking', 'completed')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.kitchen_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to kitchen_orders for tenant" ON public.kitchen_orders;
CREATE POLICY "Allow all access to kitchen_orders for tenant" ON public.kitchen_orders
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_kitchen_orders_business_status
    ON public.kitchen_orders(business_id, status);

DROP TRIGGER IF EXISTS update_kitchen_orders_modtime ON public.kitchen_orders;
CREATE TRIGGER update_kitchen_orders_modtime
    BEFORE UPDATE ON public.kitchen_orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- kitchen_display.html dùng Supabase Realtime (sự kiện INSERT + UPDATE) để hiện vé
-- mới và đổi trạng thái ngay lập tức — bảng phải được thêm vào realtime publication,
-- nếu không insert/update vẫn lưu đúng nhưng màn hình bếp chỉ thấy sau khi tải lại
-- trang thủ công, không tự động. Chạy 1 lần; an toàn khi chạy lại (no-op nếu đã có).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime' AND tablename = 'kitchen_orders'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.kitchen_orders;
    END IF;
END $$;


-- ==================================================================================
-- PHẦN 3/3 — CẦU NỐI KIẾN TRÚC HR (AN TOÀN, KHÔNG ĐỤNG HỆ CHẤM CÔNG ĐANG CHẠY)
-- ==================================================================================

-- Vì sao là cầu nối chứ không gộp toàn bộ: khảo sát cho thấy `employees`/`chamcong`
-- là hệ chấm công/lương thật, độc lập hoàn toàn, tích hợp sâu (theo dõi GPS, ảnh
-- check-in, sản lượng/hàng lỗi, chia tiền tip, điểm kudo, đồng bộ offline) trải
-- rộng trên 17 template đang chạy thật, khoá bằng mã nhân viên dạng chuỗi `ma_nv` —
-- khác cấu trúc hoàn toàn với `staff.id` (số tự tăng). Gộp toàn bộ về `staff.id`
-- ngay đêm trước khi go-live là hành động rủi ro cao hơn hẳn mục tiêu thật sự (làm
-- cho cấu hình lương ở cauhinh_luong.html chảy được vào bảng lương thật). File này
-- chỉ thêm 1 liên kết TÙY CHỌN — hoàn toàn cộng thêm, không đổi hành vi gì cho tới
-- khi admin chủ động tạo liên kết qua dropdown mới trong cauhinh_luong.html, và
-- công thức tính lương đang đúng của bangluong.html được giữ nguyên không đổi.

-- ALTER TABLE employees ADD COLUMN IF NOT EXISTS staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL;

--CREATE INDEX IF NOT EXISTS idx_employees_staff_id ON employees(staff_id);
