-- ==================================================================================
-- BITPAW OS MULTITENANT ENTERPRISE PLATFORM - FULL CLEAN DATABASE SCHEMA
-- Target Database Engine: PostgreSQL 15+ / Supabase compatible
-- Architect: Senior Supabase Database Architect
-- ==================================================================================

-- ----------------------------------------------------------------------------------
-- 0. CLEAN OLD SCHEMA (DROP EXISTING VIEWS & TABLES SAFELY)
-- ----------------------------------------------------------------------------------

-- Drop views first to avoid cascade dependency issues
DROP VIEW IF EXISTS template_registry CASCADE;
DROP VIEW IF EXISTS industry_registry CASCADE;
DROP VIEW IF EXISTS module_registry CASCADE;
DROP VIEW IF EXISTS permission_registry CASCADE;

-- Drop public business tables
DROP TABLE IF EXISTS backup_logs CASCADE;
DROP TABLE IF EXISTS bot_messages CASCADE;
DROP TABLE IF EXISTS bot_customers CASCADE;
DROP TABLE IF EXISTS customer_feedback CASCADE;
DROP TABLE IF EXISTS cskh_clicks CASCADE;
DROP TABLE IF EXISTS cskh_requests CASCADE;
DROP TABLE IF EXISTS cskh_config CASCADE;
DROP TABLE IF EXISTS promotions CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS user_logs CASCADE;
DROP TABLE IF EXISTS payment_transactions CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS karaoke_rooms CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS table_orders CASCADE;
DROP TABLE IF EXISTS dining_tables CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS salary_configs CASCADE;
DROP TABLE IF EXISTS payroll CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS license_codes CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS businesses CASCADE;

-- Drop AI Nurturing tables
DROP TABLE IF EXISTS ai_recommendations CASCADE;
DROP TABLE IF EXISTS message_logs CASCADE;
DROP TABLE IF EXISTS campaign_messages CASCADE;
DROP TABLE IF EXISTS message_templates CASCADE;
DROP TABLE IF EXISTS campaign_steps CASCADE;
DROP TABLE IF EXISTS nurturing_campaigns CASCADE;
DROP TABLE IF EXISTS nurturing_segments CASCADE;
DROP TABLE IF EXISTS message_threads CASCADE;
DROP TABLE IF EXISTS customer_events CASCADE;
DROP TABLE IF EXISTS customer_tags CASCADE;
DROP TABLE IF EXISTS customer_profiles CASCADE;
DROP TABLE IF EXISTS platform_connections CASCADE;

-- Drop Registry tables
DROP TABLE IF EXISTS templates_registry CASCADE;
DROP TABLE IF EXISTS navigation_items CASCADE;
DROP TABLE IF EXISTS industries CASCADE;
DROP TABLE IF EXISTS business_modules CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS feature_registry CASCADE;
DROP TABLE IF EXISTS route_registry CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS role_registry CASCADE;

-- ----------------------------------------------------------------------------------
-- EXTENSIONS & UTILITIES
-- ----------------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Automatic updated_at timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- ==================================================================================
-- PART I: TENANCY, ACCOUNTS & USER PROFILES
-- ==================================================================================

-- 1. BUSINESSES & TENANCY MODEL
CREATE TABLE businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    industry_code TEXT NOT NULL,
    license_key TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. USER PROFILES & ACCOUNTS (Linked with auth.users)
CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'admin' CHECK (role IN ('superadmin', 'admin', 'staff', 'customer')),
    business_id UUID REFERENCES businesses(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. CENTRAL LICENSE REGISTRY (Activations engine)
CREATE TABLE license_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key TEXT UNIQUE NOT NULL,
    nganh_nghe TEXT NOT NULL,
    trang_thai TEXT DEFAULT 'Sẵn sàng' CHECK (trang_thai IN ('Sẵn sàng', 'Đã kích hoạt', 'Đã khóa')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==================================================================================
-- PART II: CORE BUSINESS OPERATIONS (RETAIL, F&B, SPA, NAILS, KARAOKE)
-- ==================================================================================

-- 4. STAFF & HUMAN RESOURCES (BIGINT PK for Flask high-fidelity compatibility)
CREATE TABLE staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    role TEXT NOT NULL,
    commission_rate NUMERIC DEFAULT 0 CHECK (commission_rate >= 0 AND commission_rate <= 100),
    is_active BOOLEAN DEFAULT true,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 5. ATTENDANCE & TIMECARDS (Chấm công định vị & chuyên cần)
CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE,
    clock_in TIMESTAMPTZ NOT NULL,
    clock_out TIMESTAMPTZ,
    latitude_in NUMERIC,
    longitude_in NUMERIC,
    latitude_out NUMERIC,
    longitude_out NUMERIC,
    status TEXT DEFAULT 'Present' CHECK (status IN ('Present', 'Late', 'Absent', 'On Leave')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. PAYROLL SYSTEM (Kết toán bảng lương tự động)
CREATE TABLE payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE,
    month_year TEXT NOT NULL, -- Format 'MM/YYYY'
    base_salary NUMERIC NOT NULL DEFAULT 0 CHECK (base_salary >= 0),
    allowance NUMERIC DEFAULT 0 CHECK (allowance >= 0),
    commission NUMERIC DEFAULT 0 CHECK (commission >= 0),
    deduction NUMERIC DEFAULT 0 CHECK (deduction >= 0),
    net_salary NUMERIC NOT NULL DEFAULT 0 CHECK (net_salary >= 0),
    status TEXT DEFAULT 'Unpaid' CHECK (status IN ('Unpaid', 'Paid', 'Pending')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 7. SALARY CONFIGURATIONS (Cấu hình lương cơ bản nhân sự)
CREATE TABLE salary_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE UNIQUE,
    base_salary NUMERIC NOT NULL DEFAULT 0 CHECK (base_salary >= 0),
    allowance NUMERIC DEFAULT 0 CHECK (allowance >= 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 8. CUSTOMERS DATABASE (Core CRM repository)
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    gender TEXT,
    dob DATE,
    tier TEXT DEFAULT 'Normal' CHECK (tier IN ('Normal', 'VIP', 'VVIP', 'Silver', 'Gold')),
    loyalty_points INTEGER DEFAULT 0 CHECK (loyalty_points >= 0),
    total_spent NUMERIC DEFAULT 0 CHECK (total_spent >= 0),
    join_date DATE DEFAULT CURRENT_DATE,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 9. PRODUCTS & SERVICES CATALOG (Dùng chung cho hàng hóa bán lẻ & F&B và các liệu trình Spa/Nails)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    channel_type TEXT DEFAULT 'retail' CHECK (channel_type IN ('retail', 'spa', 'nail', 'fnb')),
    stock INTEGER DEFAULT 0,
    price NUMERIC NOT NULL CHECK (price >= 0),
    cost_price NUMERIC DEFAULT 0 CHECK (cost_price >= 0),
    image TEXT,
    is_active INTEGER DEFAULT 1 CHECK (is_active IN (0, 1)),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 10. DINING TABLES (Sơ đồ bàn phục vụ F&B / Karaoke)
CREATE TABLE dining_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Còn trống' CHECK (status IN ('Còn trống', 'Đang phục vụ', 'Đã đặt trước')),
    qr_token TEXT UNIQUE NOT NULL,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 11. TABLE ORDERS (Giỏ hàng/Giao dịch treo tạm thời tại bàn POS)
CREATE TABLE table_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT REFERENCES dining_tables(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 12. TRANSACTIONS & BILLING (Hóa đơn hoàn tất)
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code TEXT UNIQUE NOT NULL,
    channel TEXT DEFAULT 'retail' CHECK (channel IN ('retail', 'fnb', 'spa', 'nail', 'karaoke')),
    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 13. ORDER ITEM ENTRIES (Chi tiết giao dịch hóa đơn)
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price NUMERIC NOT NULL CHECK (price >= 0),
    total_price NUMERIC NOT NULL CHECK (total_price >= 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 14. BOOKING & SCHEDULING (Lịch hẹn dịch vụ Spa/Nail/Bàn tiệc)
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    service_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,
    book_time TIMESTAMPTZ NOT NULL,
    note TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 15. KARAOKE ROOMS (Quản lý phòng hát bida tính giờ tự động)
CREATE TABLE karaoke_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Trống' CHECK (status IN ('Trống', 'Đang chơi', 'Đã đặt trước')),
    price_per_hour NUMERIC NOT NULL CHECK (price_per_hour >= 0),
    start_time TIMESTAMPTZ,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 16. EXPENSES LEDGER (Sổ quỹ ghi nhận chi tiêu)
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL CHECK (amount >= 0),
    expense_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

-- 17. PAYMENT TRANSACTIONS (Nhật ký xử lý dòng tiền thanh toán)
CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL CHECK (amount >= 0),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 18. SYSTEM & AUDIT LOGS (Nhật ký kiểm toán hoạt động)
CREATE TABLE user_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT,
    action TEXT NOT NULL,
    description TEXT,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

-- 19. SYSTEM CONFIGURATIONS & SETTINGS (Khóa chính key-business_id)
CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    value TEXT,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(key, business_id)
);

-- 20. MARKETING & PROMOTIONS (Quản lý chương trình khuyến mãi)
CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed_amount')),
    discount_value NUMERIC NOT NULL CHECK (discount_value >= 0),
    start_date DATE,
    end_date DATE,
    usage_limit INTEGER DEFAULT 100 CHECK (usage_limit >= 0),
    product_ids JSONB DEFAULT '[]'::JSONB,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'expired', 'disabled')),
    used_count INTEGER DEFAULT 0 CHECK (used_count >= 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==================================================================================
-- PART III: AI BOT & CUSTOMER SERVICE MASCOT CHAT WIDGET
-- ==================================================================================

-- 21. CSKH WIDGET CONFIGURATION
CREATE TABLE cskh_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotline TEXT DEFAULT '0794678904',
    zalo_link TEXT DEFAULT 'https://zalo.me/0794678904',
    messenger_link TEXT DEFAULT 'https://www.facebook.com/chuyhieuhong',
    email TEXT DEFAULT 'hodinhsang30052003@gmail.com',
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 22. CSKH SUPPORT REQUESTS
CREATE TABLE cskh_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'ignored')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 23. CSKH CHANNEL INTERACTIONS LOGS
CREATE TABLE cskh_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    channel TEXT NOT NULL,
    clicked_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

-- 24. CUSTOMER SERVICE QUALITY FEEDBACK
CREATE TABLE customer_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

-- 25. AI CHATBOT INTERACTIVE CLIENTS (TEXT PK for local mock ids compatibility)
CREATE TABLE bot_customers (
    id TEXT PRIMARY KEY,
    full_name TEXT,
    last_message TEXT,
    last_message_time TIMESTAMPTZ,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 26. AI CHATBOT MESSAGES RECORDS
CREATE TABLE bot_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT REFERENCES bot_customers(id) ON DELETE CASCADE,
    sender_type TEXT CHECK (sender_type IN ('customer', 'staff', 'ai')),
    content TEXT NOT NULL,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 27. COMPONENT BACKUP LOGS
CREATE TABLE backup_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT UNIQUE NOT NULL,
    user_email TEXT,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ==================================================================================
-- PART IV: CRM AI NURTURING & MARKETING CAMPAIGNS (ZALO, FACEBOOK, SMS)
-- ==================================================================================

-- 28. SOCIAL PLATFORM CHANNELS CONNECTIONS
CREATE TABLE platform_connections (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    platform TEXT NOT NULL, -- 'messenger', 'zalo_oa', 'whatsapp', 'webform'
    connection_status TEXT DEFAULT 'DISCONNECTED' CHECK (connection_status IN ('CONNECTED', 'DISCONNECTED', 'PAUSED')),
    config_data TEXT, -- JSON Configurations/Tokens stored as text
    connected_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 29. CRM CUSTOMER PROFILE INSIGHTS (TEXT PK for SQLite sync integration)
CREATE TABLE customer_profiles (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    industry TEXT,
    source_platform TEXT,
    last_purchase_at TIMESTAMPTZ,
    total_spending NUMERIC DEFAULT 0,
    services_of_interest TEXT, -- comma-separated tags
    nurturing_status TEXT DEFAULT 'NEW' CHECK (nurturing_status IN ('NEW', 'REGULAR', 'HIBERNATING', 'NEEDS_CARE', 'ABOUT_TO_REPURCHASE', 'CHURN_RISK')),
    ai_notes TEXT,
    potential_score NUMERIC DEFAULT 50 CHECK (potential_score >= 0 AND potential_score <= 100),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 30. CRM CUSTOMER TAGS
CREATE TABLE customer_tags (
    id TEXT PRIMARY KEY,
    customer_id TEXT REFERENCES customer_profiles(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 31. CRM CUSTOMER EVENTS LOGS
CREATE TABLE customer_events (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    customer_id TEXT REFERENCES customer_profiles(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'checkout', 'booking', 'opt-out', 'visit'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 32. MESSAGE THREADS LOGS
CREATE TABLE message_threads (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    customer_id TEXT REFERENCES customer_profiles(id) ON DELETE CASCADE,
    channel TEXT NOT NULL, -- 'messenger', 'zalo', 'whatsapp'
    sender_role TEXT NOT NULL CHECK (sender_role IN ('AI', 'CUSTOMER', 'OWNER')),
    message_content TEXT NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT now()
);

-- 33. CRM NURTURING TARGET COHORTS / SEGMENTS
CREATE TABLE nurturing_segments (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    filter_criteria TEXT, -- JSON query criteria stored as text
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 34. CRM AUTOMATIONS & MARKETING CAMPAIGNS
CREATE TABLE nurturing_campaigns (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    target_segment_id TEXT REFERENCES nurturing_segments(id) ON DELETE SET NULL,
    campaign_goal TEXT CHECK (campaign_goal IN ('RECALL', 'UPSELL', 'REVIEW', 'BIRTHDAY', 'PROMO')),
    channel TEXT CHECK (channel IN ('FB', 'ZALO', 'WHATSAPP', 'SMS')),
    tone TEXT CHECK (tone IN ('friendly', 'premium', 'close', 'urgent', 'professional')),
    is_active INTEGER DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 35. CAMPAIGN ACTION STEPS SCHEDULE
CREATE TABLE campaign_steps (
    id TEXT PRIMARY KEY,
    campaign_id TEXT REFERENCES nurturing_campaigns(id) ON DELETE CASCADE,
    day_delay INTEGER NOT NULL CHECK (day_delay >= 0),
    step_title TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 36. CRM SYSTEM MESSAGE TEMPLATES
CREATE TABLE message_templates (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    industry TEXT NOT NULL,
    campaign_goal TEXT NOT NULL,
    tone TEXT NOT NULL,
    template_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 37. DISPATCH QUEUE & CAMPAIGN MESSAGES
CREATE TABLE campaign_messages (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    campaign_id TEXT REFERENCES nurturing_campaigns(id) ON DELETE CASCADE,
    customer_id TEXT REFERENCES customer_profiles(id) ON DELETE CASCADE,
    step_delay INTEGER NOT NULL,
    message_body TEXT NOT NULL,
    approval_status TEXT DEFAULT 'PENDING' CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    scheduled_send_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 38. DISPATCH HISTORY / MESSAGE LOGS
CREATE TABLE message_logs (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    customer_id TEXT REFERENCES customer_profiles(id) ON DELETE SET NULL,
    recipient_address TEXT,
    channel TEXT NOT NULL,
    message_content TEXT NOT NULL,
    delivery_status TEXT DEFAULT 'SENT' CHECK (delivery_status IN ('SENT', 'DELIVERED', 'FAILED')),
    sent_at TIMESTAMPTZ DEFAULT now()
);

-- 39. AI MARKETING INSIGHT RECOMMENDATIONS
CREATE TABLE ai_recommendations (
    id TEXT PRIMARY KEY,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    insight_type TEXT NOT NULL CHECK (insight_type IN ('CHURN_ALERT', 'CAMPAIGN_SUGGESTION', 'REVENUE_OPTIMIZE')),
    recommendation_text TEXT NOT NULL,
    is_resolved INTEGER DEFAULT 0 CHECK (is_resolved IN (0, 1)),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ==================================================================================
-- PART V: ENTERPRISE METADATA & COMPONENT REGISTRY (SAAS FRAMEWORK)
-- ==================================================================================

-- 40. SYSTEM PERMISSION REGISTRY
CREATE TABLE permissions (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 41. SAAS MODULE REGISTRY
CREATE TABLE business_modules (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT CHECK (category IN ('core', 'erp', 'hr', 'pos', 'cskh', 'ai')),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 42. BUSINESS INDUSTRIES REGISTRY
CREATE TABLE industries (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    description TEXT,
    redirect_after_login TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 43. SYSTEM DYNAMIC NAVIGATION MAP
CREATE TABLE navigation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code TEXT REFERENCES business_modules(code) ON DELETE CASCADE,
    industry_code TEXT REFERENCES industries(code) ON DELETE CASCADE,
    label TEXT NOT NULL,
    icon TEXT,
    url_path TEXT NOT NULL,
    sort_order INTEGER DEFAULT 99,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 44. DYNAMIC VIEW & TEMPLATES REGISTRY
CREATE TABLE templates_registry (
    template_name TEXT PRIMARY KEY,
    file_path TEXT NOT NULL,
    route_name TEXT,
    url_path TEXT,
    module_code TEXT REFERENCES business_modules(code) ON DELETE SET NULL,
    display_name TEXT NOT NULL,
    description TEXT,
    required_permission TEXT REFERENCES permissions(code) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 99,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==================================================================================
-- PART VI: OPTIONAL REGISTRY MAPPINGS & SECURITY ROLES (RBAC SUPPORT)
-- ==================================================================================

-- 45. SECURITY ROLES
CREATE TABLE role_registry (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 46. SECURITY ROLE-PERMISSIONS CORRELATION
CREATE TABLE role_permissions (
    role_code TEXT REFERENCES role_registry(code) ON DELETE CASCADE,
    permission_code TEXT REFERENCES permissions(code) ON DELETE CASCADE,
    PRIMARY KEY (role_code, permission_code)
);

-- 47. MODULE FEATURE FLAGS CONTROL
CREATE TABLE feature_registry (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    module_code TEXT REFERENCES business_modules(code) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT true,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 48. FLASK FLIGHT-PLAN API GATEWAY ROUTES
CREATE TABLE route_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint TEXT UNIQUE NOT NULL, -- Flask endpoint identifier
    url_path TEXT NOT NULL,
    request_method TEXT DEFAULT 'GET' CHECK (request_method IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH')),
    module_code TEXT REFERENCES business_modules(code) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ==================================================================================
-- PART VII: HIGH-PERFORMANCE BACKWARD-COMPATIBLE SYSTEM VIEWS
-- ==================================================================================

-- 1. VIEW FOR PERMISSIONS REGISTRY
CREATE OR REPLACE VIEW permission_registry AS 
SELECT code, name, description, created_at 
FROM permissions;

-- 2. VIEW FOR MODULES REGISTRY
CREATE OR REPLACE VIEW module_registry AS 
SELECT code, name, description, category, is_active, created_at, updated_at 
FROM business_modules;

-- 3. VIEW FOR INDUSTRIES REGISTRY
CREATE OR REPLACE VIEW industry_registry AS 
SELECT code, name, icon, description, redirect_after_login, created_at, updated_at 
FROM industries;

-- 4. VIEW FOR TEMPLATE VIEW REGISTRY
CREATE OR REPLACE VIEW template_registry AS 
SELECT template_name, file_path, route_name, url_path, module_code, display_name, description, required_permission, is_active, sort_order, created_at, updated_at 
FROM templates_registry;

-- ==================================================================================
-- PART VIII: OPTIMIZED DATABASE INDEXES (TENANT ISOLATION SPEED BOOST)
-- ==================================================================================

-- Core tenant indexes
CREATE INDEX IF NOT EXISTS idx_staff_business_id ON staff(business_id);
CREATE INDEX IF NOT EXISTS idx_attendance_staff_id ON attendance(staff_id);
CREATE INDEX IF NOT EXISTS idx_attendance_business_id ON attendance(business_id);
CREATE INDEX IF NOT EXISTS idx_payroll_staff_id ON payroll(staff_id);
CREATE INDEX IF NOT EXISTS idx_payroll_business_id ON payroll(business_id);
CREATE INDEX IF NOT EXISTS idx_salary_configs_staff_id ON salary_configs(staff_id);
CREATE INDEX IF NOT EXISTS idx_salary_configs_business_id ON salary_configs(business_id);
CREATE INDEX IF NOT EXISTS idx_customers_business_id ON customers(business_id);
CREATE INDEX IF NOT EXISTS idx_products_business_id ON products(business_id);
CREATE INDEX IF NOT EXISTS idx_dining_tables_business_id ON dining_tables(business_id);
CREATE INDEX IF NOT EXISTS idx_table_orders_table_id ON table_orders(table_id);
CREATE INDEX IF NOT EXISTS idx_table_orders_product_id ON table_orders(product_id);
CREATE INDEX IF NOT EXISTS idx_orders_business_id ON orders(business_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_appointments_business_id ON appointments(business_id);
CREATE INDEX IF NOT EXISTS idx_appointments_staff_id ON appointments(staff_id);
CREATE INDEX IF NOT EXISTS idx_karaoke_rooms_business_id ON karaoke_rooms(business_id);
CREATE INDEX IF NOT EXISTS idx_expenses_business_id ON expenses(business_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_business_id ON payment_transactions(business_id);
CREATE INDEX IF NOT EXISTS idx_promotions_business_id ON promotions(business_id);
CREATE INDEX IF NOT EXISTS idx_user_logs_business_id ON user_logs(business_id);
CREATE INDEX IF NOT EXISTS idx_system_settings_business_id ON system_settings(business_id);
CREATE INDEX IF NOT EXISTS idx_cskh_config_business_id ON cskh_config(business_id);
CREATE INDEX IF NOT EXISTS idx_cskh_requests_business_id ON cskh_requests(business_id);
CREATE INDEX IF NOT EXISTS idx_cskh_clicks_business_id ON cskh_clicks(business_id);
CREATE INDEX IF NOT EXISTS idx_customer_feedback_business_id ON customer_feedback(business_id);
CREATE INDEX IF NOT EXISTS idx_customer_feedback_order_id ON customer_feedback(order_id);
CREATE INDEX IF NOT EXISTS idx_bot_customers_business_id ON bot_customers(business_id);
CREATE INDEX IF NOT EXISTS idx_bot_messages_customer_id ON bot_messages(customer_id);
CREATE INDEX IF NOT EXISTS idx_bot_messages_business_id ON bot_messages(business_id);
CREATE INDEX IF NOT EXISTS idx_backup_logs_business_id ON backup_logs(business_id);

-- AI Nurturing indexes
CREATE INDEX IF NOT EXISTS idx_platform_connections_business_id ON platform_connections(business_id);
CREATE INDEX IF NOT EXISTS idx_customer_profiles_business_id ON customer_profiles(business_id);
CREATE INDEX IF NOT EXISTS idx_customer_tags_customer_id ON customer_tags(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_events_business_id ON customer_events(business_id);
CREATE INDEX IF NOT EXISTS idx_customer_events_customer_id ON customer_events(customer_id);
CREATE INDEX IF NOT EXISTS idx_message_threads_business_id ON message_threads(business_id);
CREATE INDEX IF NOT EXISTS idx_message_threads_customer_id ON message_threads(customer_id);
CREATE INDEX IF NOT EXISTS idx_nurturing_segments_business_id ON nurturing_segments(business_id);
CREATE INDEX IF NOT EXISTS idx_nurturing_campaign_business_id ON nurturing_campaigns(business_id);
CREATE INDEX IF NOT EXISTS idx_nurturing_campaign_segment_id ON nurturing_campaigns(target_segment_id);
CREATE INDEX IF NOT EXISTS idx_campaign_steps_campaign_id ON campaign_steps(campaign_id);
CREATE INDEX IF NOT EXISTS idx_message_templates_business_id ON message_templates(business_id);
CREATE INDEX IF NOT EXISTS idx_campaign_messages_business_id ON campaign_messages(business_id);
CREATE INDEX IF NOT EXISTS idx_campaign_messages_campaign_id ON campaign_messages(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_messages_customer_id ON campaign_messages(customer_id);
CREATE INDEX IF NOT EXISTS idx_message_logs_business_id ON message_logs(business_id);
CREATE INDEX IF NOT EXISTS idx_message_logs_customer_id ON message_logs(customer_id);
CREATE INDEX IF NOT EXISTS idx_ai_recommendations_business_id ON ai_recommendations(business_id);

-- System Registry indices
CREATE INDEX IF NOT EXISTS idx_feature_module ON feature_registry(module_code);
CREATE INDEX IF NOT EXISTS idx_route_module ON route_registry(module_code);
CREATE INDEX IF NOT EXISTS idx_template_module ON templates_registry(module_code);
CREATE INDEX IF NOT EXISTS idx_navigation_items_module ON navigation_items(module_code);
CREATE INDEX IF NOT EXISTS idx_navigation_items_industry ON navigation_items(industry_code);
CREATE INDEX IF NOT EXISTS idx_role_permissions_perm ON role_permissions(permission_code);

-- ==================================================================================
-- PART IX: AUTO TIMESTAMP MODIFICATION TRIGGERS
-- ==================================================================================

CREATE TRIGGER update_businesses_modtime BEFORE UPDATE ON businesses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_license_codes_modtime BEFORE UPDATE ON license_codes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_staff_modtime BEFORE UPDATE ON staff FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payroll_modtime BEFORE UPDATE ON payroll FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_salary_configs_modtime BEFORE UPDATE ON salary_configs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_customers_modtime BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_products_modtime BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_dining_tables_modtime BEFORE UPDATE ON dining_tables FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_appointments_modtime BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_karaoke_rooms_modtime BEFORE UPDATE ON karaoke_rooms FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payment_transactions_modtime BEFORE UPDATE ON payment_transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_system_settings_modtime BEFORE UPDATE ON system_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_promotions_modtime BEFORE UPDATE ON promotions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_cskh_config_modtime BEFORE UPDATE ON cskh_config FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- AI Nurturing triggers
CREATE TRIGGER update_platform_connections_modtime BEFORE UPDATE ON platform_connections FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_customer_profiles_modtime BEFORE UPDATE ON customer_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_nurturing_campaigns_modtime BEFORE UPDATE ON nurturing_campaigns FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Registry metadata triggers
CREATE TRIGGER update_industries_modtime BEFORE UPDATE ON industries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_business_modules_modtime BEFORE UPDATE ON business_modules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_templates_registry_modtime BEFORE UPDATE ON templates_registry FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==================================================================================
-- PART X: SECURITY AND ROW LEVEL SECURITY (RLS) POLICIES
-- ==================================================================================

-- Enable RLS on all tables
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE license_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll ENABLE ROW LEVEL SECURITY;
ALTER TABLE salary_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE dining_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE table_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE karaoke_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cskh_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE cskh_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE cskh_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_logs ENABLE ROW LEVEL SECURITY;

-- Enable RLS on AI Nurturing
ALTER TABLE platform_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE nurturing_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE nurturing_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_recommendations ENABLE ROW LEVEL SECURITY;

-- Enable RLS on Registry
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE industries ENABLE ROW LEVEL SECURITY;
ALTER TABLE navigation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE feature_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE route_registry ENABLE ROW LEVEL SECURITY;

-- Create resilient bypass policies for backend Flask connection compatibility (anon & authenticated)
CREATE POLICY "Allow all on businesses" ON businesses FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on profiles" ON profiles FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on license_codes" ON license_codes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on staff" ON staff FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on attendance" ON attendance FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on payroll" ON payroll FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on salary_configs" ON salary_configs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on customers" ON customers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on products" ON products FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on dining_tables" ON dining_tables FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on table_orders" ON table_orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on orders" ON orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on order_items" ON order_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on appointments" ON appointments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on karaoke_rooms" ON karaoke_rooms FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on expenses" ON expenses FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on payment_transactions" ON payment_transactions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on user_logs" ON user_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on system_settings" ON system_settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on promotions" ON promotions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on cskh_config" ON cskh_config FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on cskh_requests" ON cskh_requests FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on cskh_clicks" ON cskh_clicks FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on customer_feedback" ON customer_feedback FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on bot_customers" ON bot_customers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on bot_messages" ON bot_messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on backup_logs" ON backup_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Bypass policies for AI Nurturing
CREATE POLICY "Allow all on platform_connections" ON platform_connections FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on customer_profiles" ON customer_profiles FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on customer_tags" ON customer_tags FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on customer_events" ON customer_events FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on message_threads" ON message_threads FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on nurturing_segments" ON nurturing_segments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on nurturing_campaigns" ON nurturing_campaigns FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on campaign_steps" ON campaign_steps FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on message_templates" ON message_templates FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on campaign_messages" ON campaign_messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on message_logs" ON message_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on ai_recommendations" ON ai_recommendations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Bypass policies for Registry metadata
CREATE POLICY "Allow all on permissions" ON permissions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on business_modules" ON business_modules FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on industries" ON industries FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on navigation_items" ON navigation_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on templates_registry" ON templates_registry FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on role_registry" ON role_registry FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on role_permissions" ON role_permissions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on feature_registry" ON feature_registry FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on route_registry" ON route_registry FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ==================================================================================
-- PART XI: SYSTEM SEED DATA (MINIMUM STABLE ACTIVATION CODES)
-- ==================================================================================

-- Dynamic seeding of starting license keys
INSERT INTO license_codes (license_key, nganh_nghe, trang_thai) VALUES 
('KEY-RETAIL-TEST', 'retail', 'Sẵn sàng'),
('KEY-FNB-TEST', 'fnb', 'Sẵn sàng'),
('KEY-SPA-TEST', 'spa', 'Sẵn sàng'),
('KEY-NAIL-TEST', 'nail', 'Sẵn sàng'),
('KEY-KARAOKE-TEST', 'karaoke', 'Sẵn sàng'),
('KEY-HOTEL-TEST', 'hotel', 'Sẵn sàng'),
('KEY-PRODUCTION-TEST', 'production', 'Sẵn sàng'),
('KEY-TECHNICAL-TEST', 'technical', 'Sẵn sàng'),
('KEY-OFFICE-TEST', 'office', 'Sẵn sàng')
ON CONFLICT (license_key) DO NOTHING;

-- Seed system configuration defaults
INSERT INTO system_settings (key, value, business_id) VALUES 
('business_mode', 'retail', NULL)
ON CONFLICT (key, business_id) DO NOTHING;
