-- =========================================================================
-- PHASE 2: AI Bot nâng cấp, Dự báo tồn kho AI, Loyalty tự động
-- (+ Phase 2 Master Prompt 2: Multi-branch, Audit Trail, Đối soát thanh toán)
-- Chạy thủ công trong Supabase Dashboard -> SQL Editor (không tự động chạy).
-- Chạy SAU khi đã chạy supabase_rls_hr_tenant_fix.sql và
-- supabase_rls_full_tenant_fix.sql.
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1) restock_proposals — phiếu đề xuất nhập hàng do AI tạo (module Kho)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.restock_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id text NOT NULL,
    product_id BIGINT,
    product_name text,
    current_stock NUMERIC,
    avg_daily_sales NUMERIC,
    suggested_qty INTEGER,
    reason text,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'dismissed')),
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.restock_proposals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant isolation for restock_proposals" ON public.restock_proposals;
CREATE POLICY "Tenant isolation for restock_proposals" ON public.restock_proposals
    FOR ALL TO authenticated
    USING (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public')
    WITH CHECK (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public');

-- -------------------------------------------------------------------------
-- 2) loyalty_events — hàng đợi thông báo loyalty (tích điểm/lên hạng/sinh nhật)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loyalty_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id text NOT NULL,
    customer_id BIGINT,
    event_type text NOT NULL,  -- 'points_awarded' | 'tier_upgrade' | 'birthday'
    channel text NOT NULL DEFAULT 'none',  -- 'zalo' | 'facebook' | 'none'
    message text,
    status text NOT NULL DEFAULT 'queued',  -- 'queued' | 'sent' | 'failed' | 'skipped_no_channel'
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.loyalty_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant isolation for loyalty_events" ON public.loyalty_events;
CREATE POLICY "Tenant isolation for loyalty_events" ON public.loyalty_events
    FOR ALL TO authenticated
    USING (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public')
    WITH CHECK (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public');

-- -------------------------------------------------------------------------
-- 3) Cột bổ sung cho tính năng mới (an toàn, IF NOT EXISTS, không phá dữ liệu cũ)
-- -------------------------------------------------------------------------
-- ai_bot.html: cho phép tra cứu hạng/lịch sử chi tiêu theo SĐT khi khách chat
ALTER TABLE IF EXISTS public.bot_customers ADD COLUMN IF NOT EXISTS phone text;

-- customers: lưu định danh Zalo OA / Facebook Messenger để CÓ THỂ gửi thông báo thật
-- (chỉ gửi được khi khách từng nhắn qua OA/Messenger và bạn tự cập nhật 2 cột này —
-- code hiện tại chưa có luồng thu thập tự động, để trống thì hệ thống chỉ "queued", không gửi)
ALTER TABLE IF EXISTS public.customers ADD COLUMN IF NOT EXISTS zalo_user_id text;
ALTER TABLE IF EXISTS public.customers ADD COLUMN IF NOT EXISTS fb_psid text;

-- =========================================================================
-- MASTER PROMPT 2: Multi-branch, Audit Trail, Đối soát thanh toán
-- =========================================================================

-- -------------------------------------------------------------------------
-- 4) business_memberships — 1 chủ sở hữu (owner_user_id) có thể quản lý NHIỀU
--    business_id (chi nhánh). Bảng này KHÔNG scope theo business_id như các
--    bảng khác (chính nó là bảng định nghĩa quyền sở hữu), nên policy dựa
--    theo owner_user_id thay vì business_id.
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.business_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id text NOT NULL,
    business_id text NOT NULL,
    branch_name text,
    is_primary boolean DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (owner_user_id, business_id)
);
ALTER TABLE public.business_memberships ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner isolation for business_memberships" ON public.business_memberships;
CREATE POLICY "Owner isolation for business_memberships" ON public.business_memberships
    FOR ALL TO authenticated
    USING (owner_user_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public')
    WITH CHECK (owner_user_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public');

-- -------------------------------------------------------------------------
-- 5) audit_logs — nhật ký thao tác nhạy cảm (sửa giá, xoá sản phẩm, hủy đơn...)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id text NOT NULL,
    user_id text,
    action text NOT NULL,
    entity_type text,
    entity_id text,
    old_value jsonb,
    new_value jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant isolation for audit_logs" ON public.audit_logs;
CREATE POLICY "Tenant isolation for audit_logs" ON public.audit_logs
    FOR ALL TO authenticated
    USING (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public')
    WITH CHECK (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public');

-- -------------------------------------------------------------------------
-- 6) reconciliation_alerts — báo động đối soát thanh toán (cron tự tạo hàng ngày)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reconciliation_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id text NOT NULL,
    transaction_id text,
    order_code text,
    issue_type text NOT NULL,  -- 'missing_order' | 'amount_mismatch' | 'stale_pending'
    expected_amount NUMERIC,
    actual_amount NUMERIC,
    details text,
    status text NOT NULL DEFAULT 'pending',  -- 'pending' | 'resolved'
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.reconciliation_alerts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant isolation for reconciliation_alerts" ON public.reconciliation_alerts;
CREATE POLICY "Tenant isolation for reconciliation_alerts" ON public.reconciliation_alerts
    FOR ALL TO authenticated
    USING (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public')
    WITH CHECK (business_id = (auth.jwt() ->> 'business_id') AND COALESCE(auth.jwt() ->> 'scope', 'staff') <> 'qr_public');

-- LƯU Ý MASTER PROMPT 2:
--
-- 1. business_memberships/audit_logs/reconciliation_alerts là bảng MỚI hoàn toàn.
--    Riêng business_memberships sẽ tự động có dòng "chi nhánh chính" cho mỗi chủ
--    tiệm ngay lần đăng nhập tiếp theo sau khi deploy (xem app.py: _ensure_primary_membership,
--    gọi trong route /login) — không cần chạy tay, nhưng chủ tiệm nào CHƯA đăng
--    nhập lại từ sau khi deploy sẽ tạm thời không xuất hiện trong danh sách chi
--    nhánh cho tới lần đăng nhập kế tiếp.
--
-- 2. Cron hàng ngày (/api/cron/daily_tasks) liệt kê business_id đang hoạt động
--    dựa vào bảng 'products' + 'business_memberships' (bảng 'businesses' KHÔNG
--    được dùng vì không có dữ liệu thật — không tạo row khi đăng ký).
--
-- 3. Route "Tạo chi nhánh mới" (/add_branch) sinh 1 business_id (UUID) hoàn toàn
--    mới, KHÔNG cần tài khoản Supabase Auth riêng cho chi nhánh đó — chi nhánh
--    mới sẽ trống dữ liệu (chưa có sản phẩm/nhân viên/đơn hàng) cho tới khi bạn
--    chuyển sang chi nhánh đó và tự nhập liệu.

-- LƯU Ý QUAN TRỌNG:
--
-- 1. restock_proposals/loyalty_events là bảng MỚI hoàn toàn -> không có dữ liệu cũ,
--    không cần backfill business_id.
--
-- 2. Cron /api/cron/daily_tasks cần biến môi trường CRON_SECRET (tự đặt 1 chuỗi
--    ngẫu nhiên mạnh) trong .env production VÀ trong Vercel Project Settings ->
--    Environment Variables (Vercel tự động gửi header
--    "Authorization: Bearer <CRON_SECRET>" khi cron chạy, không cần cấu hình gì thêm).
--
-- 3. Gửi Zalo/Facebook thật cần thêm ZALO_OA_ACCESS_TOKEN / FB_PAGE_ACCESS_TOKEN
--    trong .env — CHƯA có 2 biến này thì mọi thông báo loyalty chỉ được ghi vào
--    loyalty_events với status='skipped_no_channel', không gửi đi đâu cả (không lỗi,
--    chỉ đơn giản là chưa có kênh gửi thật).
