-- ==================================================================================
-- BITPAW OS MULTITENANT ENTERPRISE PLATFORM - FULL DATABASE SCHEMA
-- Target Database Engine: PostgreSQL 15+ / Supabase compatible
-- ==================================================================================

-- ----------------------------------------------------------------------------------
-- EXTENSIONS & UTILITIES
-- ----------------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Automatic updated_at timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- ----------------------------------------------------------------------------------
-- 1. BUSINESSES & TENANCY MODEL
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    industry_code TEXT NOT NULL,
    license_key TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access for businesses" ON businesses FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow all access for authenticated admins on businesses" ON businesses FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_businesses_modtime
    BEFORE UPDATE ON businesses
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 2. USER PROFILES & ACCOUNTS
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'admin' CHECK (role IN ('superadmin', 'admin', 'staff', 'customer')),
    business_id UUID REFERENCES businesses(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to read their own profiles" ON profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Allow users to update their own profiles" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow superadmins all operations on profiles" ON profiles FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'superadmin')
);

CREATE TRIGGER update_profiles_modtime
    BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 3. CENTRAL LICENSE REGISTRY (kho_license)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS license_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key TEXT UNIQUE NOT NULL,
    nganh_nghe TEXT NOT NULL,
    trang_thai TEXT DEFAULT 'Sẵn sàng' CHECK (trang_thai IN ('Sẵn sàng', 'Đã kích hoạt', 'Đã khóa')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE license_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to license_codes for admins and anon" ON license_codes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_license_codes_modtime
    BEFORE UPDATE ON license_codes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 4. STAFF & HUMAN RESOURCES
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    role TEXT NOT NULL,
    commission_rate NUMERIC DEFAULT 0 CHECK (commission_rate >= 0 AND commission_rate <= 100),
    is_active BOOLEAN DEFAULT true,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to staff for tenant" ON staff FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_staff_modtime
    BEFORE UPDATE ON staff
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 5. ATTENDANCE & TIMECARDS (Chấm công)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE,
    clock_in TIMESTAMPTZ NOT NULL,
    clock_out TIMESTAMPTZ,
    latitude_in NUMERIC,
    longitude_in NUMERIC,
    latitude_out NUMERIC,
    longitude_out NUMERIC,
    status TEXT DEFAULT 'Present' CHECK (status IN ('Present', 'Late', 'Absent', 'On Leave')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to attendance for tenant" ON attendance FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 6. PAYROLL SYSTEM
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE,
    month_year TEXT NOT NULL, -- Format 'MM/YYYY'
    base_salary NUMERIC NOT NULL DEFAULT 0 CHECK (base_salary >= 0),
    allowance NUMERIC DEFAULT 0 CHECK (allowance >= 0),
    commission NUMERIC DEFAULT 0 CHECK (commission >= 0),
    deduction NUMERIC DEFAULT 0 CHECK (deduction >= 0),
    net_salary NUMERIC NOT NULL DEFAULT 0 CHECK (net_salary >= 0),
    status TEXT DEFAULT 'Unpaid' CHECK (status IN ('Unpaid', 'Paid', 'Pending')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE payroll ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to payroll for tenant" ON payroll FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_payroll_modtime
    BEFORE UPDATE ON payroll
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 7. SALARY CONFIGURATIONS
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS salary_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE UNIQUE,
    base_salary NUMERIC NOT NULL DEFAULT 0 CHECK (base_salary >= 0),
    allowance NUMERIC DEFAULT 0 CHECK (allowance >= 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE salary_configs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to salary_configs for tenant" ON salary_configs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_salary_configs_modtime
    BEFORE UPDATE ON salary_configs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 8. CUSTOMER RELATIONSHIP MANAGEMENT (CRM)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    gender TEXT,
    dob DATE,
    tier TEXT DEFAULT 'Normal' CHECK (tier IN ('Normal', 'VIP', 'VVIP', 'Silver', 'Gold')),
    loyalty_points INTEGER DEFAULT 0 CHECK (loyalty_points >= 0),
    total_spent NUMERIC DEFAULT 0 CHECK (total_spent >= 0),
    join_date DATE DEFAULT CURRENT_DATE,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to customers for tenant" ON customers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_customers_modtime
    BEFORE UPDATE ON customers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 9. PRODUCTS & SERVICES CATALOG (Dùng chung cho hàng hóa và dịch vụ Spa/Nail)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    channel_type TEXT DEFAULT 'retail' CHECK (channel_type IN ('retail', 'spa', 'nail', 'fnb')),
    stock INTEGER DEFAULT 0,
    price NUMERIC NOT NULL CHECK (price >= 0),
    cost_price NUMERIC DEFAULT 0 CHECK (cost_price >= 0),
    image TEXT,
    is_active INTEGER DEFAULT 1 CHECK (is_active IN (0, 1)),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to products for tenant" ON products FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_products_modtime
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 10. DINING TABLES (F&B / POS)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dining_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Còn trống' CHECK (status IN ('Còn trống', 'Đang phục vụ', 'Đã đặt trước')),
    qr_token TEXT UNIQUE NOT NULL,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE dining_tables ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to dining_tables for tenant" ON dining_tables FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_dining_tables_modtime
    BEFORE UPDATE ON dining_tables
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 11. TABLE ORDERS (Giỏ hàng/Giao dịch tạm thời tại bàn POS)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS table_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT REFERENCES dining_tables(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE table_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to table_orders for tenant" ON table_orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 12. TRANSACTIONS & BILLING (orders)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code TEXT UNIQUE NOT NULL,
    channel TEXT DEFAULT 'retail' CHECK (channel IN ('retail', 'fnb', 'spa', 'nail', 'karaoke')),
    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
    created_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to orders for tenant" ON orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 13. ORDER ITEM ENTRIES (order_items)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price NUMERIC NOT NULL CHECK (price >= 0),
    total_price NUMERIC NOT NULL CHECK (total_price >= 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to order_items for tenant" ON order_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 14. BOOKING & SCHEDULING (Lịch hẹn Spa)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    service_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,
    book_time TIMESTAMPTZ NOT NULL,
    note TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to appointments for tenant" ON appointments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_appointments_modtime
    BEFORE UPDATE ON appointments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 15. KARAOKE ROOMS (Tính giờ phòng Karaoke/Bida)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS karaoke_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Trống' CHECK (status IN ('Trống', 'Đang chơi', 'Đã đặt trước')),
    price_per_hour NUMERIC NOT NULL CHECK (price_per_hour >= 0),
    start_time TIMESTAMPTZ,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE karaoke_rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to karaoke_rooms for tenant" ON karaoke_rooms FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_karaoke_rooms_modtime
    BEFORE UPDATE ON karaoke_rooms
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 16. EXPENSES LEDGER (Quản lý chi tiêu)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL CHECK (amount >= 0),
    expense_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to expenses for tenant" ON expenses FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 16B. PAYMENT TRANSACTIONS (Giao dịch thanh toán)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL CHECK (amount >= 0),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to payment_transactions for tenant" ON payment_transactions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_payment_transactions_modtime
    BEFORE UPDATE ON payment_transactions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 17. SYSTEM & AUDIT LOGS (Nhật ký hệ thống)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT,
    action TEXT NOT NULL,
    description TEXT,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

ALTER TABLE user_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to user_logs for tenant" ON user_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 18. SYSTEM CONFIGURATIONS & BRAND SETTINGS (Cấu hình)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to system_settings for tenant" ON system_settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_system_settings_modtime
    BEFORE UPDATE ON system_settings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 19. MARKETING & PROMOTIONS (Khuyến mãi)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed_amount')),
    discount_value NUMERIC NOT NULL CHECK (discount_value >= 0),
    start_date DATE,
    end_date DATE,
    usage_limit INTEGER DEFAULT 100 CHECK (usage_limit >= 0),
    product_ids JSONB DEFAULT '[]'::JSONB,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'expired', 'disabled')),
    used_count INTEGER DEFAULT 0 CHECK (used_count >= 0),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to promotions for tenant" ON promotions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_promotions_modtime
    BEFORE UPDATE ON promotions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------------
-- 20. CUSTOMER SERVICE CHANNELS (CSKH)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cskh_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotline TEXT DEFAULT '0794678904',
    zalo_link TEXT DEFAULT 'https://zalo.me/0794678904',
    messenger_link TEXT DEFAULT 'https://www.facebook.com/chuyhieuhong',
    email TEXT DEFAULT 'hodinhsang30052003@gmail.com',
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE cskh_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to cskh_config for tenant" ON cskh_config FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_cskh_config_modtime
    BEFORE UPDATE ON cskh_config
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS cskh_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'ignored')),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE cskh_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to cskh_requests for tenant" ON cskh_requests FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS cskh_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    channel TEXT NOT NULL,
    clicked_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

ALTER TABLE cskh_clicks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to cskh_clicks for tenant" ON cskh_clicks FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS customer_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE
);

ALTER TABLE customer_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to customer_feedback for tenant" ON customer_feedback FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 21. REALTIME AI COPILOT CHAT
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bot_customers (
    id TEXT PRIMARY KEY, -- Text for mock ids support
    full_name TEXT,
    last_message TEXT,
    last_message_time TIMESTAMPTZ,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE bot_customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to bot_customers for tenant" ON bot_customers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS bot_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT REFERENCES bot_customers(id) ON DELETE CASCADE,
    sender_type TEXT CHECK (sender_type IN ('customer', 'staff', 'ai')),
    content TEXT NOT NULL,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE bot_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to bot_messages for tenant" ON bot_messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 22. DATA STORAGE BACKUPS
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS backup_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT UNIQUE NOT NULL,
    user_email TEXT,
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE backup_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to backup_logs for tenant" ON backup_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- DATABASE INDEXES FOR OPTIMAL QUERY PERFORMANCE
-- ----------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_staff_business_id ON staff(business_id);
CREATE INDEX IF NOT EXISTS idx_attendance_staff_id ON attendance(staff_id);
CREATE INDEX IF NOT EXISTS idx_attendance_business_id ON attendance(business_id);
CREATE INDEX IF NOT EXISTS idx_payroll_staff_id ON payroll(staff_id);
CREATE INDEX IF NOT EXISTS idx_customers_business_id ON customers(business_id);
CREATE INDEX IF NOT EXISTS idx_products_business_id ON products(business_id);
CREATE INDEX IF NOT EXISTS idx_dining_tables_business_id ON dining_tables(business_id);
CREATE INDEX IF NOT EXISTS idx_orders_business_id ON orders(business_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_appointments_business_id ON appointments(business_id);
CREATE INDEX IF NOT EXISTS idx_karaoke_rooms_business_id ON karaoke_rooms(business_id);
CREATE INDEX IF NOT EXISTS idx_expenses_business_id ON expenses(business_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_business_id ON payment_transactions(business_id);
CREATE INDEX IF NOT EXISTS idx_promotions_business_id ON promotions(business_id);
CREATE INDEX IF NOT EXISTS idx_bot_messages_customer_id ON bot_messages(customer_id);

-- ----------------------------------------------------------------------------------
-- SEED DATA FROM INDUSTRY_CONFIG FOR AUTOMATIC STARTUP SEEDING
-- ----------------------------------------------------------------------------------
-- Dynamic seeding of starting license keys in SQLite/Supabase for testing environment
INSERT INTO license_codes (license_key, nganh_nghe, trang_thai) VALUES 
('KEY-RETAIL-TEST', 'retail', 'Sẵn sàng'),
('KEY-FNB-TEST', 'fnb', 'Sẵn sàng'),
('KEY-SPA-TEST', 'spa', 'Sẵn sàng'),
('KEY-NAIL-TEST', 'nail', 'Sẵn sàng'),
('KEY-KARAOKE-TEST', 'karaoke', 'Sẵn sàng'),
('KEY-HOTEL-TEST', 'hotel', 'Sẵn sàng'),
('KEY-PRODUCTION-TEST', 'production', 'Sẵn sàng'),
('KEY-TECHNICAL-TEST', 'technical', 'Sẵn sàng'),
('KEY-OFFICE-TEST', 'office', 'Sẵn sàng')
ON CONFLICT (license_key) DO NOTHING;
