-- ==================================================================================
-- BITPAW OS - SAAS METADATA & TEMPLATE REGISTRY SCHEMA
-- Target Engine: PostgreSQL 15+ / Supabase compatible
-- ==================================================================================

-- ----------------------------------------------------------------------------------
-- 1. INDUSTRIES REGISTRY (Ngành nghề kinh doanh)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS industries (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    description TEXT,
    redirect_after_login TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE industries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to industries for tenant" ON industries FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 2. BUSINESS MODULES (Các module nghiệp vụ)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS business_modules (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE business_modules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to business_modules for tenant" ON business_modules FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 3. MODULE ROUTES MAPPING (Bản đồ điều hướng)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS module_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code TEXT REFERENCES business_modules(code) ON DELETE CASCADE,
    route_name TEXT NOT NULL,
    url_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE module_routes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to module_routes for tenant" ON module_routes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 4. SYSTEM PERMISSIONS (Quyền hạn truy cập)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS permissions (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to permissions for tenant" ON permissions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 5. TEMPLATES & VIEWS REGISTRY (Lược đồ file giao diện và metadata)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS templates_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT UNIQUE NOT NULL,
    file_path TEXT NOT NULL,
    route_name TEXT,
    url_path TEXT,
    industry_code TEXT REFERENCES industries(code) ON DELETE SET NULL,
    module_code TEXT REFERENCES business_modules(code) ON DELETE SET NULL,
    display_name TEXT,
    description TEXT,
    required_permission TEXT REFERENCES permissions(code) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE templates_registry ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to templates_registry for tenant" ON templates_registry FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 6. NAVIGATION & SIDEBAR ITEMS (Mục menu điều hướng động)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS navigation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code TEXT REFERENCES business_modules(code) ON DELETE CASCADE,
    industry_code TEXT REFERENCES industries(code) ON DELETE SET NULL,
    label TEXT NOT NULL,
    icon TEXT,
    url_path TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE navigation_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to navigation_items for tenant" ON navigation_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 7. FEATURE FLAGS (Công tắc tính năng nâng cao)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feature_flags (
    key TEXT PRIMARY KEY,
    value BOOLEAN DEFAULT false,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to feature_flags for tenant" ON feature_flags FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- 8. DEFAULT SETTINGS (Cài đặt cấu hình mặc định)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS default_settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE default_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to default_settings for tenant" ON default_settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------------
-- SYSTEM INDEXES FOR REGISTRY OPTIMIZATION
-- ----------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_templates_registry_industry_code ON templates_registry(industry_code);
CREATE INDEX IF NOT EXISTS idx_templates_registry_module_code ON templates_registry(module_code);
CREATE INDEX IF NOT EXISTS idx_navigation_items_industry_code ON navigation_items(industry_code);
CREATE INDEX IF NOT EXISTS idx_module_routes_module_code ON module_routes(module_code);
