-- ==================================================================================
-- BITPAW OS - SUPPLEMENTARY DATABASE SCHEMA PATCH
-- Target Database Engine: PostgreSQL 15+ / Supabase compatible
-- Objective: Give AI Omni-CSKH long-term memory — link orders to a customer phone
--            and store past service photos, so the bot can recall "what this
--            customer bought/had done last time" during chat.
-- Safety: purely additive (ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS).
--         Does not touch or delete any existing row.
-- ==================================================================================

-- 1. Link existing order tables to a customer phone number, so purchase history
--    can be looked up per-customer (today `orders`/`order_items` only carry business_id).
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone TEXT;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS customer_phone TEXT;

CREATE INDEX IF NOT EXISTS idx_orders_business_customer_phone
    ON orders(business_id, customer_phone);
CREATE INDEX IF NOT EXISTS idx_order_items_business_customer_phone
    ON order_items(business_id, customer_phone);

-- 2. New table to store past service photos (e.g. a nail sample from last month)
--    per customer, so the bot can reference them when the customer chats again.
CREATE TABLE IF NOT EXISTS public.service_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    customer_phone TEXT NOT NULL,
    order_item_id BIGINT REFERENCES public.order_items(id) ON DELETE SET NULL,
    image_url TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.service_photos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to service_photos for tenant" ON public.service_photos
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_service_photos_business_customer_phone
    ON public.service_photos(business_id, customer_phone);
