-- ==================================================================================
-- BITPAW OS - SUPPLEMENTARY DATABASE SCHEMA PATCH
-- Target Database Engine: PostgreSQL 15+ / Supabase compatible
-- Objective: Campaign 1 (F&B rebuild) — revive Kitchen Display with a real
--            kitchen_orders table, and support a 3-state ticket workflow
--            (pending -> cooking -> completed) as required by the business.
-- Safety: purely additive. Does not touch or delete any existing row.
-- ==================================================================================

CREATE TABLE IF NOT EXISTS public.kitchen_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID, -- = auth.users.id của chủ tiệm; không có bảng businesses riêng nên không đặt FK
    table_id BIGINT REFERENCES public.dining_tables(id) ON DELETE SET NULL,
    table_name TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'cooking', 'completed')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.kitchen_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to kitchen_orders for tenant" ON public.kitchen_orders
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_kitchen_orders_business_status
    ON public.kitchen_orders(business_id, status);

CREATE TRIGGER update_kitchen_orders_modtime
    BEFORE UPDATE ON public.kitchen_orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- kitchen_display.html relies on Supabase Realtime (INSERT + UPDATE events) to show
-- new tickets and status changes live — the table must be added to the realtime
-- publication, otherwise inserts/updates will persist correctly but the kitchen
-- screen will only ever see them after a manual refresh (loadRooms()/reload), not
-- instantly. Run this once; safe to re-run (idempotent no-op if already added).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime' AND tablename = 'kitchen_orders'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.kitchen_orders;
    END IF;
END $$;
