
        function toggleMobileMenu() { document.getElementById('mobile-menu').classList.toggle('open'); }

        function toggleLangDropdown(e) {
            e.stopPropagation();
            const wrapper = document.querySelector('.lang-wrapper');
            if (wrapper) wrapper.classList.toggle('open');
        }
        document.addEventListener('click', function (e) {
            const wrapper = document.querySelector('.lang-wrapper');
            if (wrapper && !wrapper.contains(e.target)) wrapper.classList.remove('open');
        });

        const translations = {
            vi: {
                hero_badge: '🏨 BitPaw OS: Quản Trị Vận Hành Khách Sạn & Homestay Chuyên Nghiệp',
                hero_h1: 'Quản lý khách sạn <br class="hidden sm:inline"> <span class="text-gradient-blue drop-shadow-[0_4px_25px_rgba(59,130,246,0.65)]" data-i18n="hero_sub1">không còn lệch ca, trùng phòng.</span> <br class="hidden sm:inline">',
                hero_desc: 'Một màn hình gom lịch đặt phòng, sơ đồ buồng phòng realtime, check-in di động nhanh gọn, POS chốt bill mini bar/tiền giờ chuẩn xác và AI tự động kéo khách quen.',
                hero_btn1: 'Dùng thử cho khách sạn',
                hero_btn2: 'Nhận demo quản lý phòng',
                hero_tag1: 'Sơ đồ phòng realtime',
                hero_tag2: 'POS tính tiền giờ/mini bar',
                hero_tag3: 'CRM quản lý khách lưu trú',
                hero_tag4: 'AI kéo khách mùa thấp điểm',
                hero_card1_label: 'Đặt Phòng Hôm Nay',
                hero_card1_line1: 'Phòng VIP 302 - Khách hàng',
                hero_card1_sub: 'Lễ tân check-in • 14:00 • Đã nhận',
                hero_card2_label: 'Buồng Phòng',
                hero_card2_line1: 'Phòng 201 - Đang dọn dẹp',
                hero_card2_sub: 'Công suất hôm nay: 85%',
                pain_eyebrow: 'Thực tế vận hành',
                pain_title: 'Khách sạn & Homestay đang <span class="text-gradient-blue drop-shadow-[0_2px_10px_rgba(59,130,246,0.3)]" data-i18n="hook_title2">đau đầu vì nỗi lo nào?</span>',
                pain_desc: 'Vận hành khách sạn đòi hỏi sự phối hợp mượt mà giữa lễ tân, buồng phòng và bộ phận tài chính. Dưới đây là những nỗi lo canh cánh mỗi ngày:',
                pain1_badge: 'Trùng phòng',
                pain1_title: 'Lịch đặt phòng dễ trùng lặp chéo kênh',
                pain1_desc: 'Khách đặt phòng từ các kênh OTA, Fanpage, Zalo chồng chéo. Lễ tân ghi sổ tay dễ bị sót hoặc trùng phòng làm khách đến không có phòng nhận gây ức chế cực lớn.',
                pain2_badge: 'Hao hụt',
                pain2_title: 'Thất thoát chi phí dịch vụ phụ và mini bar',
                pain2_desc: 'Nước ngọt, bia, đồ ăn nhẹ mini bar khách dùng hoặc các chi phí giặt ủi, thuê xe bị lễ tân quên ghi nhận vào bill, gây thất thoát doanh thu đáng tiếc.',
                pain3_badge: 'Mất đồng bộ',
                pain3_title: 'Lễ tân không rõ trạng thái buồng phòng',
                pain3_desc: 'Bộ phận buồng phòng dọn dẹp xong nhưng không báo kịp thời cho lễ tân. Khách đến sớm phải chờ lâu trong khi thực tế đã có phòng sạch sẵn sàng.',
                pain4_badge: 'Gian lận',
                pain4_title: 'Gian lận check-in trễ, giấu bill giờ lẻ',
                pain4_desc: 'Lễ tân cho khách thuê phòng giờ lẻ hoặc phụ thu check-out trễ bằng tiền mặt nhưng không khai báo hệ thống để đút túi riêng, làm chủ thất thoát nặng.',
                pain5_badge: 'Mất khách',
                pain5_title: 'Khách đi du lịch một lần rồi không quay lại',
                pain5_desc: 'Khách check-out xong ra về là khách sạn mất kết nối. Không ai gửi ưu đãi đặc biệt hay nhắc nhở voucher giảm giá để kích thích họ quay lại vào mùa thấp điểm.',
                pain6_badge: 'Mất kiểm soát',
                pain6_title: 'Chủ ở xa mù mờ công suất phòng thực tế',
                pain6_desc: 'Không có radar giám sát hoạt động buồng phòng realtime. Sếp ở xa luôn trong tình trạng bất an vì không biết hôm nay thu về bao nhiêu tiền mặt, bao nhiêu chuyển khoản.'
            ,
                nav_solutions: 'Giải Pháp',
                nav_features: 'Tính Năng',
                nav_pricing: 'Bảng Giá',
                nav_ai_cskh: 'AI CSKH',
                nav_lang_vi: 'Tiếng Việt',
                nav_login: 'Đăng Nhập',
                nav_trial: 'Dùng Thử Miễn Phí',
                nav_language_label: 'Ngôn ngữ:',
                hero_sub1: 'không còn lệch ca, trùng phòng.',
                hero_sub2: 'AI tự bám đuổi ưu đãi mùa thấp điểm.',
                hook_title2: 'đau đầu vì nỗi lo nào?',
                promise_label: 'SỰ KHÁC BIỆT CỦA BITPAW OS',
                promise_title: 'Biến khách sạn & homestay thành cỗ máy vận hành',
                promise_title2: 'siêu tốc, lấp đầy phòng trống mùa thấp điểm.',
                promise_desc: 'BitPaw số hóa và đồng bộ chặt chẽ buồng phòng, lễ tân và kho bãi, tạo ra trải nghiệm lưu trú cao cấp tuyệt đối cho khách hàng.',
                promise_feat1_title: 'Đặt phòng tự động',
                promise_feat1_desc: 'Khách đặt phòng trực tuyến tiện lợi, tự xác nhận khóa buồng phòng trống thông minh.',
                promise_feat2_title: 'Sơ đồ phòng realtime',
                promise_feat2_desc: 'Trực quan hóa trạng thái dọn dẹp buồng phòng Trống/Dơ/Bận tức thời trên di động.',
                promise_feat3_title: 'POS chốt bill chuẩn',
                promise_feat3_desc: 'Tự cộng tiền phòng lẻ giờ, phụ thu mini bar và tự tạo mã QR Code ngân hàng động.',
                promise_feat4_title: 'AI kéo khách cũ',
                promise_feat4_desc: 'AI bám đuổi hành vi, tự động gửi ưu đãi thu hút khách quay lại vào mùa thấp điểm.',
                workflow_label: 'LUỒNG VẬN HÀNH THỰC TẾ',
                workflow_title: 'Hành trình vận hành khách sạn',
                workflow_title2: 'số hóa trơn tru khép kín',
                workflow_desc: 'Bản đồ quy trình số hóa từ lúc đặt phòng đến buồng phòng dọn dẹp và AI chăm sóc:',
                wf1_title: 'Đặt phòng online',
                wf1_desc: 'Khách tự xem phòng trống, chọn ngày check-in và đặt phòng từ xa.',
                wf2_title: 'Lễ tân xác nhận',
                wf2_desc: 'Hệ thống tự chốt phòng và Zalo tự gửi tin nhắn chào mừng, hướng dẫn.',
                wf3_title: 'Check-in di động',
                wf3_desc: 'Khách check-in nhanh, lễ tân kích hoạt thẻ từ buồng phòng tức thời.',
                wf4_title: 'Dọn dẹp buồng phòng',
                wf4_desc: 'Bộ phận buồng phòng cập nhật buồng đã sạch lên sơ đồ di động realtime.',
                wf5_title: 'Ghi nhận mini bar',
                wf5_desc: 'Nước uống mini bar, giặt ủi được đồng bộ vào bill khách trực quan.',
                wf6_title: 'Check-out siêu tốc',
                wf6_desc: 'Lễ tân in bill nhiệt chớp nhoáng, tự cộng tiền giờ lẻ và chi phí dịch vụ.',
                wf7_title: 'QR thanh toán động',
                wf7_desc: 'POS tự tạo mã QR Code ngân hàng động giúp khách chuyển khoản an toàn.',
                wf8_title: 'AI bám đuổi ưu đãi',
                wf8_desc: 'AI tự động gửi kịch bản ưu đãi ngày vắng, kéo khách cũ ghé thăm lại.',
                features_label: 'HỆ THỐNG THỰC TẾ',
                features_title: 'Các tính năng lõi',
                features_title2: 'chuyên sâu Khách sạn & Homestay',
                features_desc: 'Tích hợp đầy đủ chức năng buồng phòng, đặt phòng thực tế hỗ trợ sếp quản lý từ xa:',
                feat1_title: 'Booking Lịch Hẹn',
                feat1_desc: 'Khách chủ động chọn phòng, ngày nhận phòng, ngày đi online từ xa cực kỳ nhanh gọn qua',
                feat1_link: 'Cổng đặt lịch online',
                feat1_cta: 'Dùng đặt phòng online',
                feat2_tag: 'Sơ đồ phòng',
                feat2_title: 'Sơ Đồ Phòng Realtime',
                feat2_desc: 'Hiển thị trực quan sơ đồ buồng phòng trống/dơ/bận giúp sếp linh hoạt xếp lịch nhận phòng, dọn phòng cho khách ở',
                feat2_link: 'QR Menu dịch vụ',
                feat2_cta: 'Dùng quản lý buồng phòng',
                feat3_title: 'Quy Trình Nhận Phòng',
                feat3_desc: 'Điều phối ca trực lễ tân, kiểm tra thông tin khách lưu trú, khai báo tạm trú trơn tru tại',
                feat3_link: 'Bảng điều phối nhân viên',
                feat3_cta: 'Dùng cho lễ tân',
                feat4_title: 'Hao Phí Dịch Vụ Mini bar',
                feat4_desc: 'Quản lý xuất nhập tồn đồ uống mini bar, nợ giặt ủi, thuê xe của từng phòng nghỉ ngơi ở',
                feat4_link: 'Báo cáo kho tự động',
                feat4_cta: 'Dùng quản lý vật tư',
                feat5_title: 'Smart POS Tính Tiền',
                feat5_desc: 'Tính tiền phòng theo ngày thường, giờ lẻ, ngày lễ, tự cộng tiền đồ uống mini bar và tạo QR động thanh toán chuyển khoản tức thì ở',
                feat5_link: 'POS tính tiền',
                feat5_cta: 'Dùng thanh toán quầy',
                feat6_title: 'Hồ Sơ Khách Lưu Trú',
                feat6_desc: 'Hồ sơ khách lưu trú đầy đủ số CMT/căn cước, lịch sử nhận trả phòng, thói quen đi du lịch chuyên nghiệp tại',
                feat6_link: 'Hồ sơ khách hàng CRM',
                feat6_cta: 'Dùng lưu lịch sử khách',
                feat7_tag: 'Báo cáo',
                feat7_title: 'Báo Cáo Công Suất Phòng',
                feat7_desc: 'Báo cáo tỷ lệ lấp đầy phòng nghỉ, doanh thu thực tế từ tiền phòng và tiền nước uống mini bar chi tiết tại',
                feat7_link: 'Báo cáo doanh thu realtime',
                feat7_cta: 'Dùng quản lý tài chính',
                feat8_title: 'AI Gợi Ý Ưu Đãi Ngày Vắng',
                feat8_desc: 'AI tự động lập kịch bản email/Zalo giới thiệu ưu đãi mùa thấp điểm cá nhân hóa dựa trên lịch sử lưu trú của khách tại',
                feat8_cta: 'Dùng thu hút khách du lịch',
                calc_title: 'Tính toán bill phòng khách sạn',
                calc_title2: 'chính xác trong 3 giây',
                calc_desc: 'Cuối giờ không lo lễ tân lúng túng cộng sổ sách hay tính sai phụ thu. Hãy điền thử hóa đơn mẫu buồng phòng để trải nghiệm:',
                calc_form_title: 'Nhập giá trị hóa đơn phòng mẫu',
                calc_label_room_type: 'Chọn Hạng Phòng Khách Sạn',
                calc_option_vip: 'Phòng VIP Suite (Đơn giá 1.200.000 ₫/ngày - Cọc trước 500.000 ₫)',
                calc_option_deluxe: 'Phòng Deluxe View Biển (Đơn giá 800.000 ₫/ngày - Cọc trước 300.000 ₫)',
                calc_option_standard: 'Phòng Standard Tiêu Chuẩn (Đơn giá 500.000 ₫/ngày - Cọc trước 200.000 ₫)',
                calc_option_custom: 'Tự nhập thông số thủ công bên dưới...',
                calc_label_price: '1. Đơn Giá Phòng (₫)',
                calc_label_nights: '2. Số Đêm Lưu Trú (Đêm)',
                calc_label_minibar: '3. Phụ Thu Mini bar / Nước Uống (₫)',
                calc_label_lateout: '4. Phụ Thu Check-out Trễ (₫)',
                calc_label_deposit: '5. Khách Đặt Cọc Trước (₫)',
                calc_label_discount: '6. Chiết Khấu Thành Viên (%)',
                calc_note: 'POS tự tạo mã QR Code ngân hàng động đã trừ cọc của khách, sếp đối soát từ xa cực kỳ nhàn nhã.',
                calc_receipt_title: 'Hóa đơn nhận trả buồng phòng',
                calc_r_price_label: 'Tiền Phòng Cơ Bản:',
                calc_r_discount_label: '- Giảm Giá Hạng Phòng (',
                calc_r_minibar_label: '+ Phụ Thu Mini bar / Nước:',
                calc_r_lateout_label: '+ Phụ Thu Check-out Trễ:',
                calc_r_deposit_label: '- Đã Khấu Trừ Đặt Cọc:',
                calc_r_final_label: 'Khách Cần Thanh Toán',
                calc_cta: 'Đăng ký dùng ngay Hotel OS',
                cskh_label: 'CỖ MÁY GIỮ KHÁCH TỰ ĐỘNG',
                cskh_title: 'Khách đi du lịch luôn có chu kỳ.',
                cskh_title2: 'Vấn đề là',
                cskh_title3: 'khách sạn có nhớ để nhắc hay không?',
                cskh_desc: 'AI tự động lập lịch và soạn tin nhắn chăm sóc khách hàng lưu trú theo chu kỳ nghỉ dưỡng, tăng tối đa cơ hội lấp đầy phòng trống:',
                cskh1_time: 'AI gợi ý • Sau 1 ngày',
                cskh_approved: 'Đã duyệt',
                cskh1_title: 'Hỏi thăm chất lượng phòng',
                cskh1_msg: '"Chào anh Hùng! 🐾 Cảm ơn anh đã lựa chọn lưu trú tại BitPaw Hotel ngày hôm qua. Phòng VIP 302 có mang lại sự thoải mái tối đa cho anh không ạ? Nếu cần dọn phòng hoặc thêm nước uống, sếp liên hệ quầy lễ tân nhé! 🏨"',
                cskh1_goal: 'Mục tiêu: Đo lường chất lượng buồng phòng & lễ tân phục vụ',
                cskh2_time: 'AI gợi ý • Sau 14 ngày',
                cskh2_title: 'Ưu đãi mùa thấp điểm',
                cskh2_msg: '"Kính gửi chị Hương! 🏨 AI BitPaw gửi tặng riêng chị voucher ưu đãi giảm 25% giá phòng Deluxe hướng biển cho kỳ công tác/du lịch tiếp theo của chị tại thành phố. Đặt lịch phòng giữ chỗ ngay hôm nay nha chị! 🌊"',
                cskh2_goal: 'Mục tiêu: Kích hoạt chi tiêu lưu trú của khách VIP ngày vắng khách',
                cskh3_time: 'AI gợi ý • Sau 45 ngày',
                cskh3_title: 'Bám đuổi khách cũ',
                cskh3_msg: '"Chào anh Nam! 🐾 Đã 45 ngày kể từ kỳ nghỉ thư giãn của anh tại BitPaw Hotel. Chúng em vừa nâng cấp bể bơi vô cực và có ưu đãi đặt phòng cuối tuần tặng buffet sáng miễn phí cho 2 người. Đặt phòng nghỉ dưỡng thôi sếp ơi! 🍷"',
                cskh3_goal: 'Mục tiêu: Duy trì kết nối thương hiệu bền vững, bám đuổi hành vi khách hàng',
                mkt_title: 'Trợ lý AI đề xuất kịch bản',
                mkt_title2: 'chạy Ads & Reels thu hút khách du lịch.',
                mkt_desc: 'Không còn lo lắng lên nội dung giới thiệu phòng ốc hay kịch bản quay phòng Deluxe lên mạng xã hội. Trợ lý AI của BitPaw tự động đề xuất content bám đuổi theo mùa:',
                mkt_item1_title: 'Tự tạo kịch bản quay video buồng phòng',
                mkt_item1_desc: 'AI gợi ý kịch bản quay cận cảnh ban công view biển lộng gió, giường nệm cao cấp trắng muốt tạo sự tin tưởng tuyệt đối.',
                mkt_item2_title: 'Gợi ý tệp khách hàng tiềm năng du lịch',
                mkt_item2_desc: 'AI tư vấn cách thiết lập bán kính và target sở thích khách đi du lịch, đi phượt để tối ưu hóa ngân sách quảng cáo.',
                mkt_term_1: '[SYSTEM] Kích hoạt phân hệ AI Marketing chuyên sâu Khách Sạn...',
                mkt_term_2: '[DATA] Phát hiện hạng phòng bán chạy nhất: "Deluxe Ocean View Double Room"',
                mkt_term_3: '&gt; AI-PROMPT: Đề xuất kịch bản TikTok Reels giới thiệu kỳ nghỉ cuối tuần',
                mkt_term_4: '🎬 PHÁT THẢO KỊCH BẢN VIDEO:',
                mkt_term_5: '- Góc quay 1:',
                mkt_term_6: 'Toàn cảnh flycam bãi biển rộng mênh mông, zoom cận vào khung cửa sổ phòng khách sạn (3 giây).',
                mkt_term_7: '- Góc quay 2:',
                mkt_term_8: 'Khách kéo rèm cửa, ánh nắng ban mai tràn vào phòng, gió biển thổi nhẹ (4 giây).',
                mkt_term_9: '- Âm thanh đề xuất:',
                mkt_term_10: 'Tiếng sóng vỗ rì rào xen lẫn nhạc chill thư thái.',
                mkt_term_11: '📝 CAPTION ĐỀ XUẤT:',
                mkt_term_12: '"Sáng thức dậy ở một nơi xa, kéo rèm ra là đại dương bao la lộng gió! 🌊 Thư giãn kỳ nghỉ cuối tuần trọn vẹn tại BitPaw Hotel với không gian phòng Deluxe Ocean View sang trọng và bể bơi vô cực ngắm hoàng hôn cực chill. Đăng ký đặt phòng hôm nay để nhận ngay voucher giảm 20% sếp nhé! 🛎️✨ #KhachSanViewBien #DuLichCuoiTuan #NghiDuongSpa #BitPawHotel"',
                mkt_term_13: '[SUCCESS] Đã đề xuất 3 kịch bản thành công. Tệp khách hàng mục tiêu: 22-45 tuổi, thích nghỉ dưỡng/du lịch, khu vực lân cận bán kính 100km.',
                trust_label: 'ĐỘ TIN CẬY TUYỆT ĐỐI',
                trust_title: 'Giải pháp vận hành khách sạn tinh gọn,',
                trust_title2: 'giảm thiểu tối đa lãng phí phòng trống',
                trust_stat1: 'Không còn trễ hay trùng lịch phòng',
                trust_stat2: 'Tăng trưởng công suất phòng ngày vắng',
                trust_stat3_num: '0 Giấy',
                trust_stat3: 'Số hóa 100% hồ sơ buồng phòng',
                trust_cta_text: 'Cần chuyên viên hỗ trợ thiết lập sơ đồ phòng và menu dịch vụ phụ?',
                trust_cta_btn: 'Chat Zalo Chuyên Viên BitPaw',
                faq_label: 'GIẢI ĐÁP THẮC MẮC',
                faq_title: 'Hỏi đáp về',
                faq1_q: '1. Homestay nhỏ hay chuỗi nhiều biệt thự nghỉ dưỡng có dùng được không?',
                faq1_a: 'Cực kỳ thích hợp. BitPaw Hotel OS hỗ trợ quản lý đa điểm, phân tách chi nhánh biệt thự nghỉ dưỡng chuyên nghiệp, đồng thời có giao diện tối giản dễ sử dụng phù hợp cho cả các căn hộ Homestay nhỏ lẻ tự vận hành.',
                faq2_q: '2. Sơ đồ trạng thái phòng realtime hoạt động ra sao?',
                faq2_a: 'Khi buồng phòng dọn dẹp xong, họ cập nhật trạng thái "Đã dọn dẹp" trực tiếp từ điện thoại di động. Lập tức sơ đồ phòng trên quầy lễ tân chuyển sang màu xanh "Sẵn sàng nhận khách" giúp điều phối check-in siêu tốc.',
                faq3_q: '3. Phần mềm có tự động tính phụ thu check-out trễ không?',
                faq3_a: 'Có. Đây là tính năng chốt bill chuyên sâu cho khách sạn. Sếp thiết lập đơn giá phụ thu theo giờ trễ (ví dụ trễ 1-2h phụ thu 10%, trễ quá 6h tính 100% giá ngày). Khi chốt hóa đơn, POS tự động tính toán chuẩn xác và minh bạch.',
                faq4_q: '4. Có quản lý được lượng tồn kho bia, nước ngọt mini bar không?',
                faq4_a: 'Hoàn toàn được. Hệ thống liên kết kho vật tư tự động. Khi lễ tân chốt bill mini bar trên hóa đơn phòng, số lượng lon bia/nước ngọt trong kho buồng phòng tự động khấu trừ, giúp phát hiện hao hụt kho nhanh chóng.',
                faq5_q: '5. Mã QR Code động chuyển khoản ngân hàng hoạt động ra sao?',
                faq5_a: 'POS chốt bill xong tự động sinh mã QR Code hiển thị to rõ trên quầy hoặc phiếu in bill. Khách quét mã, ngân hàng tự động điền đúng số tài khoản chủ khách sạn, đúng số tiền cần trả và đúng nội dung phòng, không sợ nhầm lẫn tiền bạc.',
                faq6_q: '6. Khi mua gói phần mềm tôi có được hỗ trợ phần cứng in bill và thẻ từ không?',
                faq6_a: 'Có. BitPaw Hotel OS tương thích tốt với các dòng máy in hóa đơn nhiệt LAN/Wifi và các loại thẻ từ buồng phòng phổ biến hiện nay. Chuyên viên của BitPaw hỗ trợ cấu hình và cài đặt từ xa hoàn toàn miễn phí trọn gói ban đầu cho sếp.',
                cta_title: 'Đừng để khách sạn tiếp tục mất doanh thu vì trùng lịch phòng và thất thoát mini bar!',
                cta_desc: 'Hãy để BitPaw Hotel OS quản lý toàn diện: đặt phòng online tự động, sơ đồ phòng buồng realtime, chốt bill tiền giờ lẻ và AI kéo khách mùa du lịch thấp điểm.',
                cta_btn1: 'Dùng thử hệ thống Khách Sạn',
                cta_btn2: 'Nhận tư vấn qua Zalo 24/7',
                cta_footnote: 'Phù hợp cho khách sạn nhỏ, khu nghỉ dưỡng, biệt thự biển, homestay ngoại ô, chuỗi nhiều chi nhánh tại Việt Nam và hải ngoại.',
                footer_tagline: 'Đế chế phần mềm SaaS ALL-IN-ONE tiên phong ứng dụng Radar AI, Smart POS đa ngành, Quản trị bán hàng Omni-channel và Dịch vụ Agency Marketing tại Việt Nam.',
                footer_products_title: 'Sản Phẩm',
                footer_link_pos: 'Smart POS Đa ngành',
                footer_link_agency: 'Dịch vụ AI Agency',
                footer_link_pricing: 'Bảng giá đầu tư',
                footer_legal_title: 'Pháp Lý & Bảo Mật',
                footer_terms: 'Điều khoản sử dụng',
                footer_privacy: 'Chính sách bảo mật',
                footer_payment: 'Chính sách thanh toán',
                footer_contact_title: 'Contact Bitpaw',
                footer_email_label: 'Email Công việc',
                footer_zalo_name: 'WhatsApp: (+84) 794.678.904',
                footer_fanpage_label: 'Facebook Chính Thức',
                footer_admin_login: 'Đăng Nhập Quản Trị',
                footer_designed_by: 'Thiết kế & Lập trình bởi:',
                modal_default_title: 'Tiêu đề',
                modal_close_btn: 'Đã hiểu & Đóng',
                footer_company_name: 'Bitpaw Technology LLC',
                footer_tax_info: 'Business Registration: 888999777',
                footer_address: '1390 Market Street, Suite 200, San Francisco, CA 94102, United States',
            },
            en: {
                hero_badge: '🏨 BitPaw OS: Professional Hotel & Homestay Operations Management',
                hero_h1: 'Manage your hotel <br class="hidden sm:inline"> <span class="text-gradient-blue drop-shadow-[0_4px_25px_rgba(59,130,246,0.65)]">no more shift mix-ups, no more room double-bookings.</span> <br class="hidden sm:inline">',
                hero_desc: 'One screen that gathers bookings, a realtime room floor plan, fast mobile check-in, a POS that accurately closes mini-bar/hourly bills, and AI that automatically brings back regulars.',
                hero_btn1: 'Try It For Your Hotel',
                hero_btn2: 'Get A Room Management Demo',
                hero_tag1: 'Realtime Room Floor Plan',
                hero_tag2: 'Hourly/Mini-Bar POS Billing',
                hero_tag3: 'CRM Guest Management',
                hero_tag4: 'AI Low-Season Guest Recovery',
                hero_card1_label: 'Today\'s Bookings',
                hero_card1_line1: 'VIP Room 302 - Guest',
                hero_card1_sub: 'Reception check-in • 2:00 PM • Received',
                hero_card2_label: 'Room Status',
                hero_card2_line1: 'Room 201 - Being Cleaned',
                hero_card2_sub: 'Today\'s Occupancy: 85%',
                pain_eyebrow: 'Real-World Operations',
                pain_title: 'What headaches are <span class="text-gradient-blue drop-shadow-[0_2px_10px_rgba(59,130,246,0.3)]">hotel & homestay owners facing?</span>',
                pain_desc: 'Running a hotel requires smooth coordination between reception, housekeeping, and finance. Here are the daily worries that keep owners up at night:',
                pain1_badge: 'Double-Booking',
                pain1_title: 'Cross-channel booking clashes',
                pain1_desc: 'Guests book from overlapping OTA, Fanpage, and Zalo channels. Handwritten notes easily miss or double-book a room, leaving arriving guests without a room and causing major frustration.',
                pain2_badge: 'Revenue Leaks',
                pain2_title: 'Losses on add-on services and mini-bar',
                pain2_desc: 'Sodas, beer, mini-bar snacks used by guests, or laundry/car rental costs, get forgotten by reception and never billed, causing real revenue loss.',
                pain3_badge: 'Out of Sync',
                pain3_title: 'Reception unclear on real room status',
                pain3_desc: 'Housekeeping finishes cleaning but doesn\'t notify reception in time. Early arrivals wait a long time even though a clean room is actually ready.',
                pain4_badge: 'Fraud',
                pain4_title: 'Late check-in fraud, hidden hourly bills',
                pain4_desc: 'Reception rents rooms by the hour or charges late-checkout fees in cash without recording it in the system, pocketing the money, causing serious losses for owners.',
                pain5_badge: 'Lost Guests',
                pain5_title: 'Guests travel once and never return',
                pain5_desc: 'Once guests check out, the hotel loses connection with them. No one sends special offers or discount reminders to bring them back during the low season.',
                pain6_badge: 'Lost Oversight',
                pain6_title: 'Remote owners unclear on real room occupancy',
                pain6_desc: 'No realtime radar monitoring room activity. Owners working remotely are always anxious, not knowing how much cash or bank transfer revenue came in today.'
            ,
                nav_solutions: 'Solutions',
                nav_features: 'Features',
                nav_pricing: 'Pricing',
                nav_ai_cskh: 'AI Guest Care',
                nav_lang_vi: 'Vietnamese',
                nav_login: 'Login',
                nav_trial: 'Free Trial',
                nav_language_label: 'Language:',
                hero_sub1: 'no more shift conflicts or room double-bookings.',
                hero_sub2: 'AI automatically chases low-season promotions.',
                hook_title2: 'struggling with which of these problems?',
                promise_label: 'THE BITPAW OS DIFFERENCE',
                promise_title: 'Turn Your Hotel & Homestay Into an Operating Machine',
                promise_title2: 'running at full speed, filling vacant rooms in the low season.',
                promise_desc: 'BitPaw digitizes and tightly syncs rooms, front desk, and inventory, creating a premium guest experience.',
                promise_feat1_title: 'Automated Booking',
                promise_feat1_desc: 'Guests conveniently book online, with smart auto-confirmation locking in available rooms.',
                promise_feat2_title: 'Real-Time Room Map',
                promise_feat2_desc: 'Visualizes room status (Vacant/Dirty/Occupied) instantly on mobile.',
                promise_feat3_title: 'Accurate POS Billing',
                promise_feat3_desc: 'Automatically adds hourly room charges and mini bar fees, and generates a dynamic bank QR code.',
                promise_feat4_title: 'AI Guest Win-Back',
                promise_feat4_desc: 'AI tracks guest behavior and automatically sends offers to bring guests back during the low season.',
                workflow_label: 'REAL-WORLD OPERATING FLOW',
                workflow_title: 'The Hotel Operations Journey',
                workflow_title2: 'fully digitized and seamless',
                workflow_desc: 'A digitized process map from booking to housekeeping and AI guest care:',
                wf1_title: 'Online Booking',
                wf1_desc: 'Guests browse available rooms, pick check-in dates, and book remotely.',
                wf2_title: 'Front Desk Confirms',
                wf2_desc: 'The system locks in the room and Zalo automatically sends a welcome message with instructions.',
                wf3_title: 'Mobile Check-In',
                wf3_desc: 'Guests check in quickly while the front desk instantly activates the room key card.',
                wf4_title: 'Housekeeping',
                wf4_desc: 'Housekeeping updates cleaned rooms on the real-time mobile room map.',
                wf5_title: 'Mini Bar Recording',
                wf5_desc: 'Mini bar drinks and laundry charges sync directly into the guest\'s bill.',
                wf6_title: 'Rapid Check-Out',
                wf6_desc: 'The front desk prints a thermal receipt instantly, adding hourly charges and service fees.',
                wf7_title: 'Dynamic QR Payment',
                wf7_desc: 'The POS generates a dynamic bank QR code for guests to pay securely by transfer.',
                wf8_title: 'AI Offer Retargeting',
                wf8_desc: 'AI automatically sends low-occupancy promotions to bring past guests back.',
                features_label: 'REAL-WORLD SYSTEM',
                features_title: 'Core Features',
                features_title2: 'Specialized for Hotels & Homestays',
                features_desc: 'Fully integrated room and booking functions to help you manage remotely:',
                feat1_title: 'Booking Scheduler',
                feat1_desc: 'Guests independently choose rooms, check-in and check-out dates online, quickly and remotely via the',
                feat1_link: 'Online Booking Portal',
                feat1_cta: 'Used for Online Booking',
                feat2_tag: 'Room Map',
                feat2_title: 'Real-Time Room Map',
                feat2_desc: 'Visually displays vacant/dirty/occupied room status, letting you flexibly schedule check-ins and housekeeping on the',
                feat2_link: 'Service QR Menu',
                feat2_cta: 'Used for Room Management',
                feat3_title: 'Check-In Workflow',
                feat3_desc: 'Coordinate front desk shifts, verify guest information, and handle residency declarations smoothly on the',
                feat3_link: 'Staff Dispatch Board',
                feat3_cta: 'Used by Front Desk',
                feat4_title: 'Mini Bar Usage Tracking',
                feat4_desc: 'Track mini bar stock in/out, laundry charges, and car rental for each room on the',
                feat4_link: 'Automated Inventory Reports',
                feat4_cta: 'Used for Supply Management',
                feat5_title: 'Smart POS Billing',
                feat5_desc: 'Calculates room charges for regular days, hourly stays, and holidays, adds mini bar charges, and generates instant dynamic QR payment on the',
                feat5_link: 'POS Billing',
                feat5_cta: 'Used at the Front Desk',
                feat6_title: 'Guest Stay Records',
                feat6_desc: 'Complete guest profiles with ID numbers, check-in/out history, and travel preferences on the',
                feat6_link: 'CRM Guest Profiles',
                feat6_cta: 'Used to Store Guest History',
                feat7_tag: 'Reports',
                feat7_title: 'Occupancy Reports',
                feat7_desc: 'Detailed occupancy rate and revenue reports from room charges and mini bar sales on the',
                feat7_link: 'Real-Time Revenue Reports',
                feat7_cta: 'Used for Financial Management',
                feat8_title: 'AI Low-Occupancy Offer Suggestions',
                feat8_desc: 'AI automatically drafts personalized email/Zalo campaigns for low-season offers based on each guest\'s stay history on the',
                feat8_cta: 'Used to Attract Travelers',
                calc_title: 'Hotel Room Bill Calculator',
                calc_title2: 'accurate in 3 seconds',
                calc_desc: 'No more front-desk confusion with manual ledgers or miscalculated surcharges. Try filling in a sample room invoice:',
                calc_form_title: 'Enter Sample Room Invoice Values',
                calc_label_room_type: 'Choose a Room Type',
                calc_option_vip: 'VIP Suite (1,200,000₫/night - 500,000₫ deposit)',
                calc_option_deluxe: 'Deluxe Ocean View (800,000₫/night - 300,000₫ deposit)',
                calc_option_standard: 'Standard Room (500,000₫/night - 200,000₫ deposit)',
                calc_option_custom: 'Enter custom values manually below...',
                calc_label_price: '1. Room Price (₫)',
                calc_label_nights: '2. Number of Nights',
                calc_label_minibar: '3. Mini Bar / Beverage Surcharge (₫)',
                calc_label_lateout: '4. Late Check-Out Surcharge (₫)',
                calc_label_deposit: '5. Guest Deposit Paid (₫)',
                calc_label_discount: '6. Membership Discount (%)',
                calc_note: 'The POS auto-generates a dynamic bank QR code with the deposit already deducted, making remote reconciliation effortless.',
                calc_receipt_title: 'Room Check-In/Out Invoice',
                calc_r_price_label: 'Base Room Charge:',
                calc_r_discount_label: '- Room Discount (',
                calc_r_minibar_label: '+ Mini Bar / Beverage Surcharge:',
                calc_r_lateout_label: '+ Late Check-Out Surcharge:',
                calc_r_deposit_label: '- Deposit Deducted:',
                calc_r_final_label: 'Guest Balance Due',
                calc_cta: 'Sign Up for Hotel OS Now',
                cskh_label: 'AUTOMATED GUEST RETENTION ENGINE',
                cskh_title: 'Travelers always follow a cycle.',
                cskh_title2: 'The question is,',
                cskh_title3: 'does your hotel remember to follow up?',
                cskh_desc: 'AI automatically schedules and drafts guest care messages based on travel cycles, maximizing your chances of filling vacant rooms:',
                cskh1_time: 'AI Suggested • 1 day later',
                cskh_approved: 'Approved',
                cskh1_title: 'Room Quality Follow-Up',
                cskh1_msg: '"Hi! 🐾 Thank you for staying at BitPaw Hotel yesterday. Did your VIP room provide maximum comfort? If you need housekeeping or more drinks, just contact the front desk! 🏨"',
                cskh1_goal: 'Goal: Measure room quality and front desk service satisfaction',
                cskh2_time: 'AI Suggested • 14 days later',
                cskh2_title: 'Low-Season Offer',
                cskh2_msg: '"Hello! 🏨 BitPaw\'s AI has a special 25% off voucher for our Deluxe Ocean View room for your next trip. Reserve your room today! 🌊"',
                cskh2_goal: 'Goal: Drive VIP guest bookings during low-occupancy periods',
                cskh3_time: 'AI Suggested • 45 days later',
                cskh3_title: 'Past Guest Retargeting',
                cskh3_msg: '"Hi! 🐾 It\'s been 45 days since your relaxing stay at BitPaw Hotel. We just upgraded our infinity pool and have a weekend offer with free breakfast for 2. Book your getaway now! 🍷"',
                cskh3_goal: 'Goal: Maintain long-term brand connection through guest behavior retargeting',
                mkt_title: 'AI Assistant Suggests Scripts',
                mkt_title2: 'for Ads & Reels that attract travelers.',
                mkt_desc: 'No more worrying about creating room showcase content or Deluxe room video scripts for social media. BitPaw\'s AI assistant automatically suggests seasonal content:',
                mkt_item1_title: 'Auto-Generate Room Video Scripts',
                mkt_item1_desc: 'AI suggests close-up shot scripts of the breezy ocean-view balcony and premium white bedding that build absolute trust.',
                mkt_item2_title: 'Suggest Traveler Audience Targeting',
                mkt_item2_desc: 'AI advises on setting radius and interest targeting for travelers and backpackers to optimize your ad budget.',
                mkt_term_1: '[SYSTEM] Activating specialized Hotel AI Marketing module...',
                mkt_term_2: '[DATA] Best-selling room type detected: "Deluxe Ocean View Double Room"',
                mkt_term_3: '&gt; AI-PROMPT: Suggest a TikTok Reels script showcasing a weekend getaway',
                mkt_term_4: '🎬 VIDEO SCRIPT DRAFT:',
                mkt_term_5: '- Shot 1:',
                mkt_term_6: 'Wide drone shot of the vast beach, zooming into the hotel room window (3 seconds).',
                mkt_term_7: '- Shot 2:',
                mkt_term_8: 'Guest opens the curtains, morning sunlight fills the room, sea breeze blows gently (4 seconds).',
                mkt_term_9: '- Suggested audio:',
                mkt_term_10: 'Gentle wave sounds mixed with relaxing chill music.',
                mkt_term_11: '📝 SUGGESTED CAPTION:',
                mkt_term_12: '"Wake up somewhere far away — open the curtains to an endless breezy ocean! 🌊 Enjoy a full weekend escape at BitPaw Hotel with a luxurious Deluxe Ocean View room and a chill infinity pool sunset. Book today for a 20% off voucher! 🛎️✨ #OceanViewHotel #WeekendGetaway #SpaRetreat #BitPawHotel"',
                mkt_term_13: '[SUCCESS] 3 scripts successfully generated. Target audience: 22-45 years old, interested in travel/relaxation, within a 100km radius.',
                trust_label: 'ABSOLUTE RELIABILITY',
                trust_title: 'A Lean Hotel Operations Solution,',
                trust_title2: 'minimizing vacant room waste',
                trust_stat1: 'No more late or double-booked rooms',
                trust_stat2: 'Growth in low-occupancy-day bookings',
                trust_stat3_num: '0 Paper',
                trust_stat3: '100% digitized room records',
                trust_cta_text: 'Need a specialist to help set up your room map and add-on service menu?',
                trust_cta_btn: 'Chat with a BitPaw Specialist on Zalo',
                faq_label: 'FREQUENTLY ASKED QUESTIONS',
                faq_title: 'Questions About',
                faq1_q: '1. Does it work for a small homestay as well as a chain of resort villas?',
                faq1_a: 'Absolutely. BitPaw Hotel OS supports professional multi-location management for resort villa chains, while its simple interface is just as easy to use for small, self-run homestays.',
                faq2_q: '2. How does the real-time room status map work?',
                faq2_a: 'Once housekeeping finishes cleaning, they mark the room "Cleaned" directly from their phone. The front desk\'s room map instantly turns green "Ready for Guests," enabling rapid check-in.',
                faq3_q: '3. Does the software automatically calculate late check-out fees?',
                faq3_a: 'Yes. This is a specialized hotel billing feature. You set surcharge rates by hours late (e.g., 1-2 hours late = 10% surcharge, over 6 hours late = full day rate). At checkout, the POS calculates it accurately and transparently.',
                faq4_q: '4. Can it manage mini bar beer and soft drink inventory?',
                faq4_a: 'Absolutely. The system automatically links to your supply inventory. When the front desk bills mini bar items to the room invoice, the stock count is automatically deducted, quickly flagging any shrinkage.',
                faq5_q: '5. How does the dynamic bank transfer QR code work?',
                faq5_a: 'Once the bill is closed, the POS automatically generates a large, clear QR code on the counter or printed receipt. Guests scan it and their banking app auto-fills the hotel\'s account number, exact amount, and room reference — no risk of payment errors.',
                faq6_q: '6. Does the software package include support for receipt printers and key card hardware?',
                faq6_a: 'Yes. BitPaw Hotel OS is fully compatible with common LAN/Wifi thermal receipt printers and room key card systems. BitPaw specialists provide free remote setup and configuration to get you started.',
                cta_title: 'Don\'t let your hotel keep losing revenue to room booking conflicts and mini bar shrinkage!',
                cta_desc: 'Let BitPaw Hotel OS handle it all: automated online booking, real-time room maps, hourly billing, and AI-driven low-season guest retargeting.',
                cta_btn1: 'Try the Hotel System',
                cta_btn2: 'Get 24/7 Zalo Consultation',
                cta_footnote: 'Ideal for small hotels, resorts, beach villas, suburban homestays, and multi-branch chains in Vietnam and abroad.',
                footer_tagline: 'A pioneering ALL-IN-ONE SaaS platform in Vietnam, applying AI Radar, multi-industry Smart POS, omnichannel sales management, and marketing agency services.',
                footer_products_title: 'Products',
                footer_link_pos: 'Multi-Industry Smart POS',
                footer_link_agency: 'AI Agency Services',
                footer_link_pricing: 'Pricing Plans',
                footer_legal_title: 'Legal & Security',
                footer_terms: 'Terms of Service',
                footer_privacy: 'Privacy Policy',
                footer_payment: 'Payment Policy',
                footer_contact_title: 'Contact Bitpaw',
                footer_email_label: 'Business Email',
                footer_zalo_name: 'WhatsApp: (+84) 794.678.904',
                footer_fanpage_label: 'Official Facebook',
                footer_admin_login: 'Admin Login',
                footer_designed_by: 'Designed & developed by:',
                modal_default_title: 'Title',
                modal_close_btn: 'Got it & Close',
                footer_company_name: 'Bitpaw Technology LLC',
                footer_tax_info: 'Business Registration: 888999777',
                footer_address: '1390 Market Street, Suite 200, San Francisco, CA 94102, United States',
            }
        };

        function changeLanguage(lang) {
            const icon = lang === 'vi' ? '🇻🇳' : '🇬🇧';
            const text = lang === 'vi' ? 'VN' : 'EN';
            const elIcon = document.getElementById('current-lang-icon');
            const elText = document.getElementById('current-lang-text');
            if (elIcon) elIcon.innerText = icon;
            if (elText) elText.innerText = text;
            document.querySelectorAll('[data-i18n]').forEach(el => {
                const key = el.getAttribute('data-i18n');
                if (translations[lang] && translations[lang][key]) {
                    el.innerHTML = translations[lang][key];
                }
            });
            const wrapper = document.querySelector('.lang-wrapper');
            if (wrapper) wrapper.classList.remove('open');
        }
    