-- =========================================================================
-- BitPaw SaaS Multitenant Enterprise Platform Database Schema
-- Supabase PostgreSQL DDL Script (Safe: No Drop Tables)
-- =========================================================================

-- 1. System Settings Table
CREATE TABLE IF NOT EXISTS public.system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. License Keys Table
CREATE TABLE IF NOT EXISTS public.license_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key TEXT UNIQUE NOT NULL,
    nganh_nghe TEXT NOT NULL, -- 'retail', 'fnb', 'spa', 'nail', 'karaoke', etc.
    trang_thai TEXT DEFAULT 'Sẵn sàng'::text NOT NULL, -- 'Sẵn sàng', 'Đã kích hoạt'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Businesses Directory Table
CREATE TABLE IF NOT EXISTS public.businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL, -- Reference to auth.users
    name TEXT NOT NULL,
    industry_code TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Products Inventory Table (For Retail & F&B menus)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    stock INTEGER DEFAULT 0 NOT NULL,
    is_active INTEGER DEFAULT 1 NOT NULL, -- 1: Active, 0: Deleted
    channel_type TEXT DEFAULT 'retail'::text NOT NULL, -- 'retail', 'fnb', etc.
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Spa & Nails Services Table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    duration INTEGER DEFAULT 30 NOT NULL, -- in minutes
    is_active INTEGER DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Dining Tables (For F&B / Restaurants)
CREATE TABLE IF NOT EXISTS public.dining_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    qr_token TEXT,
    status TEXT DEFAULT 'Còn trống'::text NOT NULL, -- 'Còn trống', 'Có khách', 'Đang dọn dẹp'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Table Orders Buffer Table (Active orders at F&B tables)
CREATE TABLE IF NOT EXISTS public.table_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT REFERENCES public.dining_tables(id),
    product_name TEXT NOT NULL,
    quantity INTEGER DEFAULT 1 NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    status TEXT DEFAULT 'Đang làm'::text NOT NULL, -- 'Đang làm', 'Đã phục vụ', 'Đã thanh toán'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Sales Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT,
    total_amount NUMERIC(15, 2) NOT NULL,
    payment_method TEXT DEFAULT 'Tiền mặt'::text NOT NULL, -- 'Tiền mặt', 'Chuyển khoản'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Sales Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT,
    quantity INTEGER DEFAULT 1 NOT NULL,
    total_price NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Bookings Table (For Spa & Nails Appointments)
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    service_name TEXT NOT NULL,
    booking_time TIMESTAMP WITH TIME ZONE NOT NULL,
    technician_name TEXT,
    status TEXT DEFAULT 'Chờ xác nhận'::text NOT NULL, -- 'Chờ xác nhận', 'Đã xác nhận', 'Đã xong', 'Đã hủy'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL, -- 'Nhập hàng', 'Tiền mặt bằng', 'Lương nhân sự', etc.
    amount NUMERIC(15, 2) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. Staff Management Table
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL, -- 'Quản lý', 'Thu ngân', 'Kỹ thuật viên', 'Nhân viên phục vụ'
    phone TEXT,
    salary_rate NUMERIC(15, 2) DEFAULT 0.00 NOT NULL,
    is_active INTEGER DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 13. Attendance / Timecards Log Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    industry_code TEXT NOT NULL,
    clock_in_time TIMESTAMP WITH TIME ZONE NOT NULL,
    clock_out_time TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'Đang làm'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 14. Payment Transactions Table
CREATE TABLE IF NOT EXISTS public.payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    transaction_no TEXT UNIQUE,
    amount NUMERIC(15, 2) NOT NULL,
    gateway TEXT DEFAULT 'vietqr'::text NOT NULL,
    status TEXT DEFAULT 'pending'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 15. User & Audit Logs Table
CREATE TABLE IF NOT EXISTS public.user_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    action TEXT NOT NULL,
    description TEXT,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 16. AI CRM Customer Support Configuration Table
CREATE TABLE IF NOT EXISTS public.cskh_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name TEXT NOT NULL,
    usp TEXT,
    target_audience TEXT,
    blacklist_words TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 17. AI CRM Support Requests Table
CREATE TABLE IF NOT EXISTS public.cskh_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    message TEXT,
    status TEXT DEFAULT 'pending'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 18. AI CRM Channel Clicks Table
CREATE TABLE IF NOT EXISTS public.cskh_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    channel TEXT NOT NULL, -- 'facebook', 'zalo', 'tiktok', etc.
    clicked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 19. AI Customer Feedback & Analysis Table
CREATE TABLE IF NOT EXISTS public.customer_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    feedback_text TEXT NOT NULL,
    sentiment TEXT, -- 'Tích cực', 'Tiêu cực', 'Trung lập'
    ai_response TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 20. Karaoke & Rooms Table
CREATE TABLE IF NOT EXISTS public.karaoke_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name TEXT UNIQUE NOT NULL,
    room_type TEXT DEFAULT 'Thường'::text NOT NULL, -- 'Thường', 'VIP'
    price_per_hour NUMERIC(15, 2) NOT NULL,
    status TEXT DEFAULT 'Trống'::text NOT NULL, -- 'Trống', 'Đang sử dụng'
    start_time TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- Set Up Database Indexes for Fast Query Executions
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_products_channel ON public.products(channel_type);
CREATE INDEX IF NOT EXISTS idx_attendance_staff ON public.attendance(staff_id);
CREATE INDEX IF NOT EXISTS idx_attendance_industry ON public.attendance(industry_code);
CREATE INDEX IF NOT EXISTS idx_dining_tables_status ON public.dining_tables(status);
CREATE INDEX IF NOT EXISTS idx_table_orders_table ON public.table_orders(table_id);
CREATE INDEX IF NOT EXISTS idx_bookings_time ON public.bookings(booking_time);
CREATE INDEX IF NOT EXISTS idx_orders_created ON public.orders(created_at);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_cskh_requests_status ON public.cskh_requests(status);
CREATE INDEX IF NOT EXISTS idx_karaoke_rooms_status ON public.karaoke_rooms(status);
