-- ==================================================================================
-- BITPAW OS - ENTERPRISE METADATA & COMPONENT REGISTRY SCHEMA
-- Target Engine: PostgreSQL 15+ / Supabase compatible
-- ==================================================================================

-- ----------------------------------------------------------------------------------
-- 1. INDUSTRY REGISTRY (Danh mục ngành nghề kinh doanh)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS industry_registry (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    description TEXT,
    redirect_after_login TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------------
-- 2. MODULE REGISTRY (Mục lục phân hệ nghiệp vụ SaaS)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS module_registry (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT CHECK (category IN ('core', 'erp', 'hr', 'pos', 'cskh', 'ai')),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------------
-- 3. FEATURE REGISTRY (Bảng phân chia tính năng nâng cao & công tắc v8.1)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feature_registry (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    module_code TEXT REFERENCES module_registry(code) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT true,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------------
-- 4. ROUTE REGISTRY (Sơ đồ Flask & API Gateway routes)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS route_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint TEXT UNIQUE NOT NULL, -- Flask route name (e.g., 'index', 'pos')
    url_path TEXT NOT NULL,       -- Flask url path (e.g., '/dashboard', '/pos')
    request_method TEXT DEFAULT 'GET' CHECK (request_method IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH')),
    module_code TEXT REFERENCES module_registry(code) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------------
-- 5. PERMISSION REGISTRY (Quyền hạn chi tiết trên hệ thống)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS permission_registry (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------------
-- 6. ROLE REGISTRY (Nhóm vai trò bảo mật phân quyền)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role_registry (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------------
-- 7. ROLE-PERMISSION CORRELATION (Bảng liên kết phân quyền bảo mật)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role_permissions (
    role_code TEXT REFERENCES role_registry(code) ON DELETE CASCADE,
    permission_code TEXT REFERENCES permission_registry(code) ON DELETE CASCADE,
    PRIMARY KEY (role_code, permission_code)
);

-- ----------------------------------------------------------------------------------
-- 8. TEMPLATE & VIEW REGISTRY (Cấu trúc file giao diện HTML)
-- ----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS template_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT UNIQUE NOT NULL,           -- e.g. 'pos.html'
    file_path TEXT NOT NULL,                      -- e.g. 'templates/pos.html'
    display_name TEXT NOT NULL,
    description TEXT,
    module_code TEXT REFERENCES module_registry(code) ON DELETE SET NULL,
    required_permission TEXT REFERENCES permission_registry(code) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 99,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------------
-- INDEXES FOR MAXIMUM HIGH-FIDELITY CORRELATION SPEED
-- ----------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_feature_module ON feature_registry(module_code);
CREATE INDEX IF NOT EXISTS idx_route_module ON route_registry(module_code);
CREATE INDEX IF NOT EXISTS idx_template_module ON template_registry(module_code);
CREATE INDEX IF NOT EXISTS idx_role_permissions_perm ON role_permissions(permission_code);
