-- ==================================================================================
-- BITPAW OS - SUPPLEMENTARY DATABASE SCHEMA PATCH
-- Target Database Engine: PostgreSQL 15+ / Supabase compatible
-- Architect: Senior QA + Supabase Coverage Auditor
-- Objective: Add missing ad_suggestions_log and ad_campaigns tables for AI Ad Assistant
-- ==================================================================================

-- 1. CREATE AD SUGGESTIONS LOG TABLE
CREATE TABLE IF NOT EXISTS public.ad_suggestions_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_id TEXT,
    product_name TEXT NOT NULL,
    platform TEXT NOT NULL,
    suggestions JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. CREATE AD CAMPAIGNS TABLE
CREATE TABLE IF NOT EXISTS public.ad_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_id TEXT,
    platform TEXT NOT NULL,
    name TEXT NOT NULL,
    objective TEXT,
    budget NUMERIC DEFAULT 0,
    campaign_id TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'created',
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. CREATE OPTIMIZED INDEXES FOR QUERY SPEED
CREATE INDEX IF NOT EXISTS idx_ad_suggestions_log_business_id ON public.ad_suggestions_log(business_id);
CREATE INDEX IF NOT EXISTS idx_ad_suggestions_log_platform ON public.ad_suggestions_log(platform);
CREATE INDEX IF NOT EXISTS idx_ad_campaigns_business_id ON public.ad_campaigns(business_id);
CREATE INDEX IF NOT EXISTS idx_ad_campaigns_platform ON public.ad_campaigns(platform);
CREATE INDEX IF NOT EXISTS idx_ad_campaigns_status ON public.ad_campaigns(status);
CREATE INDEX IF NOT EXISTS idx_ad_campaigns_campaign_id ON public.ad_campaigns(campaign_id);

-- 4. LINK AUTOMATIC TIMESTAMP UPDATE TRIGGER (Using update_updated_at_column)
CREATE TRIGGER update_ad_suggestions_log_modtime 
    BEFORE UPDATE ON public.ad_suggestions_log 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_ad_campaigns_modtime 
    BEFORE UPDATE ON public.ad_campaigns 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 5. ENABLE ROW LEVEL SECURITY (RLS) FOR DATA PROTECTION
ALTER TABLE public.ad_suggestions_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_campaigns ENABLE ROW LEVEL SECURITY;

-- 6. CREATE RESILIENT FLASK BACKEND BYPASS POLICIES
CREATE POLICY "Allow all on ad_suggestions_log" ON public.ad_suggestions_log FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on ad_campaigns" ON public.ad_campaigns FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
